### ISSUE TITLE
Feature Request: Single method to store new or fetch existing login with a given username and URL

### ISSUE THREAD

**Issue by tangphillip** [AgileBits/onepassword-app-extension#107]
In the Meetup iOS app, we support logging in through the new user registration form. This is so that returning users who have forgotten that they have an account can sign in with minimal friction.

Unfortunately, there's no way for us to prevent that friction for 1Password users.

I'd like to request a method for the 1Password extension to solve this issue. The method would open an editor for an entry with a given username and domain, and either present the existing password (if there's a saved password) or a password generator (if there isn't).

Since we know the user's requested username (they've just typed it) and the URL (meetup.com), we could use this new method to provide sign-in service through our sign-up form.

**Comment by rudyrichter** [comment]
+1, something that possibly mirrors the storeLoginForURLString API with its options dictionaries for requesting that a "new login" button appear in the findByURL UIView for cases where the user knows the login and created it elsewhere but hasn't yet ingested it into 1P yet.

**Comment by radazzouz** [comment]
Thanks for the suggestion @rudyrichter :+1:

**Comment by rudyrichter** [comment]
any joy?

**Comment by radazzouz** [comment]
Thanks for the followup @rudyrichter :wink: 

This is still under consideration. The change would require changes in both the App Extension API as well as in 1Password.

Please stay tuned for updates. I'll make sure to comment on this issue as soon as we have more news.

Best,

**Comment by radazzouz** [comment]
Adding @gianpispi 's vote for this feature request (see #287).

**Comment by radazzouz** [comment]
Last week we released 1Password 6.3.1 which adds the ability to create a new Login in 1Password if no matching logins were found.

Closing this issue as done.

**Comment by tangphillip** [comment]
Awesome!! Thank you so much!!

**Comment by radazzouz** [comment]
:blush:
