### ISSUE TITLE
Add the ability to save or fill other (non-Login) categories

### ISSUE THREAD

**Issue by wyllys66** [agilebits/onepassword-app-extension#117]
I have an app and would like to integrate 1Password extension support. However, it appears that the only category of password supported is the "login" type which is associated with a website URL.

My app has passwords that correspond to PGP keys.  Normally, I would create a password in the "Passwords" category (not "logins"), but there it doesn't appear that there is a way to lookup anything that is not a "login" type of password with a URL.  

Is it possible to create or find any password from any category?

**Comment by wyllys66** [comment]
Hello - I've just been working with your latest extension code and it seems to be getting closer to what I need to integrate with my app, its still not quite there.

I see that I can use the "app://..." URL designation to save information needed by my app (which is good). However, when the specific entry that my app is looking for is not there,  it then brings up a form to enter data to create a new 1Password entry (also good).  The problem is that it requires a "login" name to be entered, and in my case there is no login name, theres just a password to be saved. Also, if I use the "app://bundleIdentifier" naming convention (e.g. app://com.foo.bar), then the name of the login entry being created is just called "Com".  So, this leads me to 2 requests:

1. Add an option to hide the "Username" field when creating an entry, or at least to make it not be required prior to saving.
2. Add ability to change the default identifier name in the event that a new entry is being created.

Finally, is there any way to make iOS immediately bring up your app extension API instead of an action sheet that looks like this ?

![img_4264](https://cloud.githubusercontent.com/assets/4163874/13907975/2ac0a03c-eed0-11e5-8bdc-bcc4ea20717b.jpg)

**Comment by radazzouz** [comment]
Hi @wyllys66,

Thanks for getting back to us :+1: 

We do have plans to add the ability to allow passing additional options such as `AppExtensionTitleKey` to `findLoginForURLString:` (see #312). This should solve most of your concerns. So please keep an eye out on this repo :wink:

> Finally, is there any way to make iOS immediately bring up your app extension API instead of an action sheet that looks like this ?

No, this is how Apple designed app extensions: They "live" in the share sheet. So one cannot invoke an extension without going through a `UIActivityViewController`. For more info please take a look at [my comment](https://github.com/AgileBits/onepassword-app-extension/issues/204#issuecomment-98422857) on #204.

Hope that this helps.

**Comment by wyllys66** [comment]
Thanks!  Looking forward to future updates.

**Comment by radazzouz** [comment]
Cheers! :blush:

**Comment by alexge** [comment]
Hi @radazzouz,

I've been working on adding the 1password extension into my app. Our registration has 3 fields: Email address, Name, and Password. The user is able to fill out these fields in the app, and then tap a button to enter 1password. The Email field I've passed through as the username and the Password field as the password. The name field is passed through the `AppExtensionFieldsKey`. However, once a user reaches the 1password extension, I haven't been able to find a way to allow them to edit the Name field. Is there something that I'm missing, or is this functionality not yet part of 1password?

Thanks!

**Comment by gks** [comment]
Hi @alexge 

Once the item is saved the user should be able to edit it in the item like they do any of the other fields (username, password, URL, etc). But one of the things about this particular feature is that it requires the Pro features, which are an in-app purchase if using the standalone app and is included as part of a 1Password.com membership, our new subscription service. 

The ability to see and edit additional sections and fields is not included in the free app, so while apps like yours can save data to those sections and fields, they aren't available for users to see unless they have the Pro features, in either of the two ways it can be purchased. 

I hope that helps!

**Comment by alexge** [comment]
Hi @gks 

Thanks for getting back to me. I just wanted to clarify a few things. I've been testing on devices linked to pro accounts. This is the code that I've been using

```swift
let newLoginDetails: [String: Any] = [AppExtensionTitleKey: "myAPP", AppExtensionFieldsKey: ["name": ""]]
let passwordRequirements: [String: Any] = [AppExtensionGeneratedPasswordMinLengthKey: 8]
OnePasswordExtension.shared().storeLogin(forURLString: URL, loginDetails: newLoginDetails, passwordGenerationOptions: passwordRequirements, for: viewController, sender: sender, completion: { (loginDictionary, error) -> Void in ..... })
```

I'm not currently passing through any user inputs from my app, which is why there are no username/password fields in `newLoginDetails`. Instead, I'm letting the user fill in those fields from the extension. However, when I go into the extension, there is a `Username or email` field and a `Password` field, but no `name` field. Is that how it is supposed to work? Also, when I go into my 1password app and open this saved item, there is no `name` field for me to edit.

Any input would be helpful! Thanks!

**Comment by alexge** [comment]
Hi @gks 

Quick update, when I pass in an actual string for the `name` field, that field is showing up in the 1password app item.

**Comment by gks** [comment]
Hi @alexge 

Correct, it will show up in the app, but will not display when creating the item in the app extension. After you save and revisit the item you'll see that field there.

When you go through the process of helping the user save a new item it'll only show you the username and password fields. 

If you pass an empty string the field may be shown if you click the edit button, but any field that has an empty value will be hidden. Basically we hide items that are empty.

Your questions are unrelated to this particular issue though, if you have further questions please either create a new issue or email in at support+appex@agilebits.com and mention my name. Generally for support related inquiries I tend to prefer the email route instead as some people get notifications for every post in this project and I try not to bother them too much. Happy to help you in either way though.

**Comment by jojo0273** [comment]
![image](https://user-images.githubusercontent.com/63878522/89706618-12c6de00-d92d-11ea-90c4-91c82f0c0971.jpeg)

**Comment by jojo0273** [comment]
@

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, I'm closing out any remaining issues and branches.
