### ISSUE TITLE
when calling change password API the "done" button doesn't always dismiss  

### ISSUE THREAD

**Issue by mpvosseller** [AgileBits/onepassword-app-extension#123]
If the change password API is called but the password doesn't actually change the "Done" button in the extension UI does not dismiss the extension properly ("Done" turns into "Edit").

Contrived example using your ACME app:
- Create a new login with password = "pass1"
- Now go to the change password screen
- In all three textfields (old password, new password, confirm password) type "pass1" and hit the 1Password button.
- In the extension UI hit "Done"
- Observe that the extension is not dismissed and the "Done" button turns into "Edit".

- Expected behavior: The extension should be dismissed and the calling code should be told what the current password value is ("pass1" in this case)

**Comment by radazzouz** [comment]
We just released 1Password 5.2 and made the necessary changes in PR #143. So I am closing this issue as fixed.
