### ISSUE TITLE
Add the ability to find matching logins for more than a single URLString.

### ISSUE THREAD

**Issue by radazzouz** [AgileBits/onepassword-app-extension#131]
As requested by some of you (@alobi in #87, @honcheng in #90, @dpettigrew in #115 and @voidstern in #121), it is clear to us that we need a better `findLoginForURLString:`.

Since this change needs to be implemented in both 1Password and the App Extension API, we filed an internal issue {OPI-1870} in our bug tracker, which should be addressed soon.

I will close the related issues and will leave this one open. Please feel free to comment on this one instead.

Thanks guys!

**Comment by smileyborg** [comment]
Related, it would be great for a more formal spec on the URLString and how 1Password (and other apps that adopt this same password management extension protocol) will parse it.

For example, the spec should address these questions:
* Does the URL's protocol matter? Should it even be included? (e.g. will `http://` be handled differently than `https://`? or should URLs just be `example.com` omitting the protocol?)
* What about subdomains and other path components? It seems that 1Password strips the URL to just the base, e.g. a URLString of `sub.example.com` is treated as just `example.com` when matching against logins. I didn't test adding path components
* etc

**Comment by radazzouz** [comment]
Hi @smileyborg,

The 1Password extension, just like 1Browser, 1Password mini for Mac and 1Password for Windows, uses the naked domain to find matching Logins. Which means that `protocol://sub.example.com` will be transformed into `example.com`. In other words you can simply pass `example.com` as the value of `URLString` and the 1Password extension will find any Logins with an `example.com` naked domain.

I hope that this helps.

Cheers!

**Comment by smileyborg** [comment]
@radazzouz What I am asking for is a more formal spec, preferably in the README, that lays out exactly how this URL should be interpreted. If this spec just clarifies exactly what 1Password's behavior is, that's fine.

But this is important because this "SDK" that 1Password has pioneered is quickly becoming the canonical source code and protocol that all apps are adopting for password management. Other password management apps, such as LastPass and Keeper, are already supporting this extension protocol. So it is likewise important that there is a clearly defined spec for how the URLString should be interpreted by those apps.

**Comment by radazzouz** [comment]
Hi @smileyborg,

Thanks for getting back to me so quickly :+1: 

I totally agree with you. I think that the best place to document the URL matching logins is in code. We prefer to keep the README as small as possible. In our opinion it should contain only the **"getting started"** documentation. The more in-depth doc should be found in the code.

I just added your comment to issue #148 this way we will keep all the documentation requests in a single issue.

Have an amazing weekend!

**Comment by roustem** [comment]
We are using information from https://publicsuffix.org/ to convert full URL to a naked domain.

**Comment by khowardui** [comment]
+1 for this. Would like to have the ability to accept multiple domains

**Comment by radazzouz** [comment]
Hi guys,

We addressed this issue in the latest 1Password for iOS 5.3 betas. Meaning that there no specific action that you need to take in your integration code.

You should still use `findLoginForURLString:` the same way as before. So here’s how it works now using **ACME**:

1. Use `findLoginForURLString:@"https://www.acme.com"`
2. If the user has no matching Logins in 1Password for acme.com you’ll be offered to search among all your 1Password Logins by tapping on the “Show all Logins” button

![](https://www.evernote.com/shard/s340/sh/5c6e4cef-1e5f-4be2-a215-d37cf1fec16f/d9af3fe75ba5a86944c734892f0b3c68/deep/0/Screenshot-2015-03-04,-9-55-AM.png)

3. You can search for the desired Login. In the case, I only had a single Login that had `"https://oldacme.com"` as a URL.
4. Tap on the desired Login and it will fill the credentials into **ACME**

I am closing this issue as fixed :wink: 

Cheers!

**Comment by alobi** [comment]
Awesome stuff, thanks :smile:

**Comment by smileyborg** [comment]
Hey @radazzouz, the update to 1Password is a good improvement! I don't want to rain on the parade, but I don't think this completely addresses the problem.

From my understanding, developers are asking to submit multiple URLs for 1Password to do the initial matching against logins. The improvement you describe doesn't let this happen -- it forces the user to constantly do a manual search if the initial URL match fails. That should remain as the fallback, but ideally developers could submit 2 or more URLs to match against.

I think the main example where this would happen are things like:
* the service has multiple domains (e.g. gmail.com, google.com, etc)
* the service has changed domains (e.g. was xyz.com and is now abc.com)
* the service had no web presence originally (so it used some app-specific domain) but now does, such as Instagram and Uber

In any of the above cases, a 1Password user could have a login with just one of the two or more valid domains. So, the change you described is a step forward, but as far as I can tell the original ask behind this issue hasn't been resolved.

**Comment by radazzouz** [comment]
Hi @smileyborg,

Thanks for sharing your thoughts with us :+1:

The purpose of this change in 1Password is not to fully address the problem, but to offer a convenient way for both developers and users to overcome the scenario when no matching Login is found in the 1Password extension.

We have considered several solutions before coming up with this one such as adding support for an array of domains and even using regular expressions. But every solution we thought of had major setbacks and edge-cases. For example:

From a security perspective it is absolutely necessary to display the URL from the third party app to the user.

![](https://www.evernote.com/shard/s340/sh/77a8b376-dd46-44bd-8ce9-6afa18f21c32/1ebcadfb84f0a505ec2e764f53dd8022/deep/0/Add-the-ability-to-find-matching-logins-for-more-than-a-single-URLString.---Issue--131---AgileBits-onepassword-app-extension.png)

If the developer sends us an array of 4 or 5 domains, we need to display them all.

We believe that the current solution addresses the three scenarios that you are describing:

> the service has multiple domains (e.g. gmail.com, google.com, etc)

See @roustem 's [comment](https://github.com/AgileBits/onepassword-app-extension/issues/131#issuecomment-71780901) on #131

```"We are using information from https://publicsuffix.org/ to convert full URL to a naked domain."```

> the service has changed domains (e.g. was xyz.com and is now abc.com)

The user can use the newly improved workflow to Login and should later edit the item in 1Password for iOS (the main app) or in 1Password on any other syncing platform.

> the service had no web presence originally (so it used some app-specific domain) but now does, such as Instagram and Uber

For apps that did not have the a web URL in the first place, the user should follow the same steps as in scenario 2.

We recommend to developers who do not have a "web presence" to set their item's URL to their app's bundle identifier when saving using the **App Extension API** (`storeLoginForURLString:`). See the [**Best Practices**](https://github.com/AgileBits/onepassword-app-extension#best-practices) section of the `README`.

Please note that we are always aiming towards a similar experience offered by 1Browser, 1Password mini for Mac and 1Password Helper for Windows.

Hope that this helps!

Best,

**Comment by smileyborg** [comment]
Thanks for the reply. I understand what you're saying, although I do disagree still. I think the best UI to show matching logins for each domain would be the following:

* **Choose an item for xyz.com**
  * (some login for xyz)
* **Choose an item for abc.com**
  * (some login for abc)
  * (another login for abc)
* etc

Basically, each domain that has 1 or more matching logins would be shown as a section header in the list. Then the user would simply scroll through the list of all matches.

I think trying to make the user know that they need to update the website for each login to a new value is asking a lot -- I would bet a good chunk of money that most users are clueless about how this matching works, and will simply be frustrated that certain apps never match their logins.

**Comment by radazzouz** [comment]
Hi @smileyborg,

Thanks for getting back to us again so quickly :smiley:

When we considered coffering a method using an array of URL strings, we considered a similar implementation to the one that you are describing and here’s why we decided not to use it:

In this case the developer assumes that the user has valid data in the database: the developers assumes that the user has a login for either  "newAwesomeWebsite.com" or "oldAwesomeWebsite.com".

Unfortunately, some users may have their Login’s URL set to "newAwesome**TYPO**Website.com” (`#copyPasteProblems`) and 1Password will not find any matching Login. This can also lead to user confusion. 

Cheers buddy :wink:

**Comment by michaeldwan** [comment]
I'm a little late to the party, but I also feel the suggestion by @smileyborg provides a better user experience when a domain changes. 

Our app was recently spun out of a parent company that shared logins among a handful of popular apps. We're transitioning users to our own auth system which'll be hosted on our domain, but the vast majority of saved passwords will still be under the old domain. By only searching for a single url we practically guarantee no matches for most users.

I agree that typos are a concern, but that's a separate problem who's solution can coexist with a grouped list of matches. Forcing the user to search each time in the off event that the url has a typo puts the burden on the user which seems like a poor compromise.

Just my 2 cents! :smile:

**Comment by radazzouz** [comment]
Hi @michaeldwan,

Thanks for sharing your thought with us :+1: 

We know that this solution may not be ideal for everybody. However, we are confident that it will address the vast majority of scenarios.

For your particular situation, we strongly recommend that you let your users know about the domain change sooner rather than later. Users should ideally update their 1Password Logins otherwise they will encounter the same issue (no Logins found for the new domain) in 1Password for Mac and Windows.

The logic used to match Logins by the naked domain (used in `findLoginForURLString:`) is identical in 1Password for Mac and 1Password for Windows. So users who haven't updated their Logins will not be able to fill into your new website using the browser extensions.

Hope that this helps :smile: 

Best,

**Comment by roustem** [comment]
I wonder if we should allow specifying more than one domain in the `findLoginForURLString:` method. It could look something like this:

```
findLoginForURLString:@"abc.com,xyz.com"
```

**Comment by udimov** [comment]
Please, add multiple domains feature to 1Password extension App. We have to domains https://topvisor.ru and https://topvisor.com and our ios app works with both. Now we transfer to 1password extension domain similar to iOS interface language, but some users, for example, can be English interface and Russian login. It would be great to transfer both domains (topvisor.ru and topvisor.com) to Extension, that users can choose account for login.

**Comment by guidedways** [comment]
Sadly this solution does not really work for most apps that rely on a username and password. Most usernames these days for IMAP accounts can be made-up domains or from domains other than the server they're connecting to (Outlook / Exchange / Google for example). This is quite annoying as one cannot find anything based on the username itself rather than using a domain name search. Please allow us the ability to do this.

**Comment by radazzouz** [comment]
Hi @guidedways,

`findLoginForURLString:` mimics the user experience that we have in 1Password mini on Mac, 1Password Helper on Windows and 1Browser on iOS: It shows all matching logins for a given URL string in the selected vault regardless of the username.

> one cannot find anything based on the username itself rather than using a domain name search.

As a third party developer, one can not know in advance about the user’s username, so I don’t see how a `findLoginForURLString:username:` method would be useful in this case.

As a user, one can always search in the list of matching logins for a specific username. So if the user has 10 Logins stored in 1Password for “domain.com”, the user can always search for the username in the search field.

**Matching Logins for acme.com**

![](https://www.evernote.com/l/AVQeFGIXbLdGQ7EfmipHvJUKDFRgPSmwFJgB/image.png)

**Searching among the matching Logins for a specific username**

![](https://www.evernote.com/l/AVTbIFtCMz9H3qrLebqLWSeXiaZwMgOG1X8B/image.png)

Let me know if this helps.
