### ISSUE TITLE
Social sharing options disappear when adding 1password extension item to UIActivityViewController

### ISSUE THREAD

**Issue by swemoney** [AgileBits/onepassword-app-extension#141]
I'm using the low-level branch of the 1Password extension in my browser application so I can add the 1Password extension item to the existing UIActivityViewController. A very odd problem is that when I add the returned extensionItem to my UIActivityViewController's items, I lose Facebook and Twitter from the sharing options. When I remove the 1Password extension item, the Facebook and Twitter options come back.

**Comment by radazzouz** [comment]
Closing this issue. Since it has been addressed in the `ACME Browser (WebView Filling Demo for iOS - Low Level project)` target from the [add-low-level-api](https://github.com/AgileBits/onepassword-app-extension/tree/add-low-level-api) branch.
