### ISSUE TITLE
Improve the in-code documentation

### ISSUE THREAD

**Issue by radazzouz** [AgileBits/onepassword-app-extension#148]
* Better document the methods and their arguments in-code (for example address @jaredsinclair 's [comment](https://github.com/AgileBits/onepassword-app-extension/issues/147#issuecomment-67236594) from issue #147).
* Update the README so that it references the Low Level API.

**Comment by smileyborg** [comment]
I'd specifically like to see some documentation on each of the constants/keys `#define`'ed at the top of the header.

**Comment by radazzouz** [comment]
Linking @smileyborg 's [comment](https://github.com/AgileBits/onepassword-app-extension/issues/131#issuecomment-70748948) from issue #131 :+1: 

We should also document the matching Login URLString format.
