### ISSUE TITLE
Light Image Assets

### ISSUE THREAD

**Issue by jhersh** [AgileBits/onepassword-app-extension#154]
Ahoy AgileBits and thanks again for all you do with 1PW.

We'd love to use your app extension in our apps, but our login screens use dark and/or colored backgrounds on which the black 1PW image doesn't look so great. I'm hoping you'd be able to add white or light-colored versions of your assets, specifically the button. Thanks!

**Comment by radazzouz** [comment]
Hey @jhersh,

Thanks so much for the kind words and for taking the time to write to us :+1: 

I just filed an internal bug in our issue tracker and pinged or designer. More updates will come soon.

In the meantime, if you want, you can change the colour of the assets yourself and use them in your app :smile: 

Cheers!

<font size='1' color='grey'><i>ref: OPI-2197</i></font>

**Comment by smileyborg** [comment]
:+1: For now, I found that setting the UIButton to 50% alpha with the black asset works well.

**Comment by smileyborg** [comment]
Also, please consider providing highlighted state assets!

**Comment by radazzouz** [comment]
Hi @smileyborg,

Thanks for sharing the alpha workaround :+1: 

We just merged PR #157, which should address this issue.

As far as the highlighting state of the icons goes, we think that it's best for developers to provide the assets in case they want the 1Password icon highlighted state to match thew rest of their app's highlighted state.

I will close this issue for now.

Cheers!

**Comment by jhersh** [comment]
Thanks @radazzouz! Would you consider bumping the version and updating the podspec?

**Comment by radazzouz** [comment]
Hi @jhersh,

We cannot update the podspec yet since master contains changes that requires our users to have the upcoming 1Password update.

Thanks for understanding!

Best,

**Comment by AdamPro13** [comment]
@radazzouz are there any plans to bumping the version sometime soon now that the update went live?

**Comment by radazzouz** [comment]
Hi @AdamPro13,

As I mentioned in my previous comment, right now master contains changes that aren't fully supported in the current version of 1Password for iOS from the App Store.

Our plan is to push a new update for the **1Password App Extension API** really soon. As soon as the new version of 1Password will be available in the App Store.

You can always use the version from master in your code (assuming that you are not using CocoaPods).

Have an amazing weekend!
