### ISSUE TITLE
Add support for Phonegap / Cordova

### ISSUE THREAD

**Issue by sandstrom** [AgileBits/onepassword-app-extension#155]
Any chance you'll be able to wrap a Cordova/Phonegap plugin around this?

I'm a big fan of 1Password, so that would be super-useful!

**Comment by radazzouz** [comment]
Hi @sandstrom,

Thanks for taking the time to write in and for the kind words :+1: 

After doing some googling it seems that PhoneGap / Cordova does indeed support iOS frameworks. See this [StackOverflow post](http://stackoverflow.com/questions/18653413/how-to-copy-a-custom-ios-framework-using-plugin-xml-on-phonegap-3).

The 1Password App Extension API can also be built as a framework. Please checkout from our [add-framework-support](https://github.com/AgileBits/onepassword-app-extension/tree/add-framework-support) branch.

Hope that this helps :wink: 

Cheers!

**Comment by sandstrom** [comment]
Hi @radazzouz,

Yes, I know. My suggestion is that you should wrap your Extension API in a Cordova plugin, and publish it in their plugin library. The process is fairly simple, it's more or less a standardized shim around the code you already have.

The benefit you would get is wider option of your application (more apps with support for 1Password).

For example Adjust (analytics) has wrapped their iOS/Android SDKs in a Cordova plugin:
https://github.com/adjust/cordova_sdk

Same for notificare (push notifications):
https://github.com/Notificare/notificare-push-lib-cordova

Both do this to drive adoption of their SDKs.

**Comment by schnti** [comment]
Are there any news on this?

**Comment by radazzouz** [comment]
Thanks for the followup @schnti :+1: 

Before we wrap the App Extension API into a Cordova plugin we need to make sure that it is fully supported, which means that we need to write the demo apps in Cordova to test them.

@schnti @sandstrom did you try and wrap the App Extension API into a Cordova plugin locally and try to integrate it into your apps? If so please feel free to PR the changes.

Best,

**Comment by sandstrom** [comment]
@radazzouz No, we haven't. Happy to hear you're looking at this.

**Comment by radazzouz** [comment]
Hi @sandstrom,

We are not promising that we will add support for PhoneGap/Cordova. As I mentioned in my previous reply, this feature requires more than just wrapping the 1Password App Extension API in a Cordova plugin. It requires a sample app, extensive testing and support.

So I am reopening this issue and will label it as `under consideration`. This way other developers can see it and hopefully get involved :wink: 

Cheers!

**Comment by schnti** [comment]
@radazzouz We are currently in the process writing a extension and demo app.

**Comment by radazzouz** [comment]
You rock @schnti :+1: 

I look forward to seeing it.

Thanks buddy!

**Comment by staugaard** [comment]
Any news?

**Comment by softBarbarian** [comment]
This feature would be very nice to have!

**Comment by softBarbarian** [comment]
@schnti any progress on the cordova plugin?
cc @staugaard @radazzouz @sandstrom

**Comment by softBarbarian** [comment]
@schnti I might have some time to help you with the plugin development. I will let you know once i hear back from you.

**Comment by softBarbarian** [comment]
Also if anyone cares i did find this plugin on npm registry https://www.npmjs.com/package/onepassword-app-extension-phonegap-ios
that was uploaded by @EdTorbett

**Comment by softBarbarian** [comment]
@EdTorbett any luck with using 1Password in your cordova app?

**Comment by EdTorbett** [comment]
I built/uploaded what was there, but couldn't get it to work :(

**Comment by softBarbarian** [comment]
@schnti I was wonder if there is any progress on the plugin?

**Comment by softBarbarian** [comment]
...crickets...

**Comment by tdotcspot** [comment]
+1

**Comment by schnti** [comment]
We're done!
https://github.com/SPIRIT-21/cordova-plugin-1password
https://www.npmjs.com/package/cordova-plugin-1password

```
cordova plugin add cordova-plugin-1password
```

**Comment by sandstrom** [comment]
@schnti Awesome! :boat:

**Comment by andydoyle** [comment]
Great work @schnti!

**Comment by radazzouz** [comment]
Thanks so much for taking the time to write this Cordova plugin, @schnti's! 👍

We (AgileBits) cannot officially endorse, support or maintain the aforementioned plugin, therefore we cannot encourage third party developers to use it. 

Our official App Extension API uses native Apple APIs such as NSExtension, NSItemProvider, etc. These APIs are known to be secure. They are essentially an XPC encapsulation and we know that no third party can intercept the data that 1Password sends to the native host app.

This is not the case with the design of this plugin which uses a fork of this repo and third party libraries that we do not provide, support or maintain.

It is our responsibility towards our users and developers who add 1Password to their apps using this API to ensure that the whole experience is as convenient as secure.

Thank you for understanding. I am closing this issue for now as `won't do`.

If you have any question or concerns, please let us know.

**Comment by sandstrom** [comment]
@radazzouz A Cordova app is basically a web-view running within a native app. Since you have extensions running in all major browsers in theory a Cordova extension running in webkit + iOS-native should be able to be as secure as the things you've built. But I understand if you cannot endorse/support something you haven't produced yourself.

**Comment by jamesdixon** [comment]
Would love to see official support for Cordova. With the proliferation of Ionic and Cordova in general, you'd certainly benefit from wider adoption. Unfortunately, @schnti's plugin isn't maintained, though nice work.
