### ISSUE TITLE
Add the ability to retrieve TOTP if Available.

### ISSUE THREAD

**Issue by brianmichel** [AgileBits/onepassword-app-extension#163]
It would be awesome to grab the TFA token if one exists for a given URL! Absolutely love the new integration, but just want developer access to this field too.

**Comment by jpgoldberg** [comment]
On 2015-02-02, at 2:58 PM, Brian Michel <notifications@github.com> wrote:

> It would be awesome to grab the TFA token if one exists for a given URL!

Hi Brian!

Can you clarify whether you are looking for the the one time password (the temporary 6 digit code) or the actual stored secret.

If the former, can you let us know what would be most useful in terms of reporting the time left on it. (Each code is valid for a 30 second window, and I’m not sure what the extension ought to return when, say, it is 29 seconds into a 30 second window.)

If you are looking to actually extract the long term shared secret that is used for generating the one time password, I’d like to know why. (I don’t think this is what you are asking for, but I want to make sure I understand.)

> Absolutely love the new integration,

Thanks!

-j

–- 
Jeffrey Goldberg
Chief Defender Against the Dark Arts @ AgileBits
http://agilebits.com

**Comment by brianmichel** [comment]
Hey Jeffrey, 
 I'd just like to get access to the 6 digit code so we can have a typing free workflow. It might be nice to know how many seconds are left if the token is about to expire too.

**Comment by radazzouz** [comment]
Hey Brian!

Thanks for letting us know that you are interested in retrieving the TOTP using the 1Password App Extension API :+1: 

Cheers!
