### ISSUE TITLE
Push 1.1.2 .podspec to Cocoapods

### ISSUE THREAD

**Issue by alobi** [AgileBits/onepassword-app-extension#175]
The current .posdpec is versioned 1.1.2, but the available one on Cocoapods.org is 1.1.

:beers:

**Comment by radazzouz** [comment]
Hi @alobi,

Thanks for reminding us to update the podspec :+1: 

I just submitted a [PR](https://github.com/CocoaPods/Specs/pull/12967) to update the podspec to the latest stable version. I will close this issue as soon as my PR is merged.

:beers: to you too :wink:

**Comment by tapi** [comment]
This looks like it may be an issue with trunk, looking now

**Comment by radazzouz** [comment]
Thanks @tapi!

**Comment by tapi** [comment]
in the mean time if you use ```pod '1PasswordExtension', '~> 1.1'``` instead of explicitly asking for 1.1.2 I think it will pull in the closest match which would resolve in you getting 1.1.2.

**Comment by alobi** [comment]
No worries, we're able to pull in 1.1.2 temporarily via:

```objc
pod '1PasswordExtension', :git => 'git@github.com:AgileBits/onepassword-app-extension.git', :tag => '1.1.2'
```

**Comment by tapi** [comment]
It looks like its just caching on the Cocoapods web search.
If you do ```pod repo update``` then 1.1.2 will show up when you do a pod search from the command line.

Related: https://github.com/CocoaPods/Specs/pull/12968

**Comment by alobi** [comment]
All good, thanks!
