### ISSUE TITLE
Warning: The image set "onepassword-extension" has an unassigned image.

### ISSUE THREAD

**Issue by rmaz** [AgileBits/onepassword-app-extension#177]
There are a couple of dead images in the extension assets folder which are producing warnings during build time:

onepassword-extension@3x~regular.png
onepassword-extension-light@3x~regular.png

**Comment by radazzouz** [comment]
Hi @rmaz,

Thanks for taking the time to write in :+1: 

These images are left there on purpose, please refer to my [comment](https://github.com/AgileBits/onepassword-app-extension/pull/167#issuecomment-72916370) in PR #167 for more information.

Please let me know if there's anything else I can do to help :wink: 

Cheers!

**Comment by rmaz** [comment]
so just to be clear, you are leaving unused assets in the project for a device that doesn't yet exist, which will generate warnings for all consumers of your library? this does not seem like a very sensible solution.

why not just delete them for now and restore them from git in the very unlikely event that you will need them? or just switch to using pdfs for everything?

**Comment by radazzouz** [comment]
Hi @rmaz,

Thanks for getting back to us :+1: 

> so just to be clear, you are leaving unused assets in the project for a device that doesn't yet exist, which will generate warnings for all consumers of your library? this does not seem like a very sensible solution.

We prefer to leave the assets in the repo in case other developers want to use them: Some developers may want to use the higher resolution assets. Again, if the warnings are really a problem for you, you can always remove them locally.

> why not just delete them for now and restore them from git in the very unlikely event that you will need them?

We could also do this and we will if this starts to become an issue for more developers.

> or just switch to using pdfs for everything?

We did try using PDFs internally and we didn't like how they render, so we decided to go back to good old PNGs.

Have an amazing weekend!

**Comment by ryanmaxwell** [comment]
I agree with @rmaz, these warnings are a pain in the ass. I try very hard to keep my project warning free - and these assets are often the entire warning in my project. @radazzouz If you didn't realise, if you have a project with no warnings, Xcode doesn't bump you across to the warnings tab with every build. 

I don't like having to modify a pod to fix what seems like a poor choice in default behaviour. And with every pod update, I'll have to do it again. Please reconsider this behaviour.

**Comment by radazzouz** [comment]
Hi @ryanmaxwell,

We fixed the warnings in PR #196. If you pull from master you shouldn't see warnings anymore.

Best,
