### ISSUE TITLE
Filling web view fields reports success but does not fill fields

### ISSUE THREAD

**Issue by patr1ck** [AgileBits/onepassword-app-extension#201]
I'm using OnePasswordExtension to do "Use Case # 4" (fill a web view for oauth):

```objc
- (IBAction)fillUsing1Password:(id)sender {
    [[OnePasswordExtension sharedExtension] fillLoginIntoWebView:self.webView forViewController:self sender:sender completion:^(BOOL success, NSError *error) {
        if (!success) {
            NSLog(@"Failed to fill login in webview: <%@>", error);
        }
    }];
}
```

I'm running into an issue on iOS 8.3 where the extension is successfully called, a login is found and selected, but the login details don't get filled into the fields in the web view, despite the completion block being called with success = YES.

I noticed while trying to debug this that if I placed a breakpoint in the completion block, but then continued after checking the success value (or doing anything, or nothing) the fields would be filled. This led to the discovery that I could just wrap the `evaluateJavaScript:...` call around OnePasswordExtension.m#L446 in a pair of dispatch_async calls with a sleep(1) (_super hacky_, I know) and that would fix the issue:

```objc
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            sleep(1);
            dispatch_async(dispatch_get_main_queue(), ^{
                
                [((WKWebView *)webView) evaluateJavaScript:scriptSource completionHandler:^(NSString *result, NSError *evaluationError) {
                    BOOL success = (result != nil);
                    NSError *error = nil;

                    if (!success) {
                        NSLog(@"Cannot executeFillScript, evaluateJavaScript failed: %@", evaluationError);
                        error = [OnePasswordExtension failedToFillFieldsErrorWithLocalizedErrorMessage:NSLocalizedString(@"Failed to fill web page because script could not be evaluated", @"1Password Extension Error Message") underlyingError:error];
                    }

                    if (completion) {
                        completion(success, error);
                    }
                }];
                
            });
        });
```

I haven't spent too much time looking at the actual OnePasswordExtension.m code so I'm not sure where the actual cause is, but let me know if you have any trouble reproducing this, I'm happy to help.

**Comment by radazzouz** [comment]
Hi @patr1ck,

Thanks so much for taking the time to write in :+1: 

Can you please send us the URL that you using so we can try and reproduce it on our end? Please note that half of the "magic" happens in 1Password. So it is likely that we have in issue in our 1Password Brain. If that's the case, you don't need the "hacky" approach, we should fix it on our end. 

Which version of 1Password are you using? Is it the latest `5.4`?

And finally, just out of curiosity, how are you running 1Password in the simulator?

I look forward to your reply :wink: 

Enjoy your Friday evening!

**Comment by patr1ck** [comment]
Hey @radazzouz, Thanks for the quick response!

1Password version 5.4, yes. 

No, I can't reproduce it in the ACME Browser app – interesting, I perhaps something is set up incorrectly with my WKWebView. I'll compare the setup of the ACME browser with my own.

Oops, totally not happening in the simulator, obviously. I'll edit that out, no idea what I was thinking.

Thanks. :)

**Comment by radazzouz** [comment]
That's a good sign @patr1ck, **ACME Browser** uses `WKWebView`, please make sure that you have a similar setup in your app.

Cheers!

**Comment by patr1ck** [comment]
(I'm gonna close this out until I can confirm it's actually an issue with OnePasswordExtension and not my own code.)

**Comment by patr1ck** [comment]
Ah figured it out: my view controller was calling the webview's loadRequest: in viewDidAppear:. This meant that the webview was being reloaded after the 1Password extension was closed, causing the filled fields to be replaced with new, unfilled fields, and explains the strange behavior seen when debugging.

Sorry for the noise!

**Comment by radazzouz** [comment]
That's great news indeed, @patr1ck! Thanks for letting us know that you've figured it all out and for sharing with us :+1: 

> Sorry for the noise!

No need to apologize, I hope that your issue will help other developers fix it should they encounter it.

Cheers buddy!

**Comment by bok-** [comment]
It just did! I was doing exactly the same thing. Moved the `loadRequest:` call into `viewDidLoad:` and we're golden. :)

Thanks guys.

**Comment by radazzouz** [comment]
Awesome @bok- ! I am really glad that this issue helped you solve your issue too. YAY!
