### ISSUE TITLE
Jump right into 1Password extension instead of opening share sheet

### ISSUE THREAD

**Issue by bringel** [AgileBits/onepassword-app-extension#204]
Is there a way to jump right into the 1Password extension instead of opening the share sheet when tapping the button you set up? Right now tapping the button brings up this:
![screen shot 2015-05-02 at 10 20 40 am](https://cloud.githubusercontent.com/assets/305085/7441615/12508e0a-f0b5-11e4-9e1b-cff9811ac368.png).

I'd love to either open right to the master password screen.

**Comment by radazzouz** [comment]
Hi @bringel,

Thanks for taking the time to write in :+1:

This is something that we have explored when we first wrote the App Extension API, we wanted it so badly too. However, the Apple APIs do not allow us to _"bypass"_ the share sheet when we call the 1Password extension or any other extension for that matter. 

So no, it is not possible to call the 1Password extension without going through the iOS share sheet. iOS extensions _”live"_ in the share sheet and the only way to invoke an iOS extension is by using a *UIActivityViewController* which brings up the share sheet.

Hope that this helps. I will close this issue for now.

Enjoy your weekend! :smile:
