### ISSUE TITLE
Including 1Password in Swift inside an already existing ActivityViewController

### ISSUE THREAD

**Issue by PastaCoder** [AgileBits/onepassword-app-extension#208]
Hi,
I have sent this by email as well since I didn't know where will be answered sooner.

I have a Browser app written in Swift, and I have managed to add the 1Password Button and having it fill login data on the Web View. It works great. The thing is, I already have a Share button that shows a share sheet on my app and I would like to include 1Password in the Share button instead of the 1Password button, so I won’t be serving 2 Share buttons with varying share options.

Since the 1Password extension is in Objective-C and the app is in Swift, I don’t know how to make it work (including 1Password in the Share button). Can you help me with this matter?

Here’s the code for the Share button:
`@IBAction func _shareButton(sender: UIButton) {`

    var shareContent = _searchBar.text

    if let myWebsite = NSURL(string: "\(_searchBar.text)")
    {
        let objectsToShare = [myWebsite]
        let activityVC = UIActivityViewController(activityItems: objectsToShare, applicationActivities: nil)
        if UIDevice.currentDevice().userInterfaceIdiom == .Pad {
            // The app is running on an iPad, so you have to wrap it in a UIPopOverController
            var popOver: UIPopoverController = UIPopoverController(contentViewController: activityVC)
            let rect = CGRect(origin: CGPoint(x: 559, y: 44), size: CGSize(width: 38, height: 32))
            // if your "share" button is a UIBarButtonItem
            popOver.presentPopoverFromRect(rect, inView: self.view, permittedArrowDirections: UIPopoverArrowDirection.Any, animated: true)

        } else {
            self.presentViewController(activityVC, animated: true, completion: nil)

        }
    }
`}`

And here is the code I use for the 1Password button:
`@IBAction func onePasswordButton(sender: AnyObject) {
    OnePasswordExtension.sharedExtension().fillItemIntoWebView(self._webView, forViewController: self, sender: sender, showOnlyLogins: false, completion: {(Bool) in
        // error handling
    })
}`

I also have another question. Should I always update my OnePasswordExtension.h and .m files as soon as you make changes? since I see in this [issue](https://github.com/AgileBits/onepassword-app-extension/issues/207) you updated the methods.

Thanks :)

PastaCoder

**Comment by radazzouz** [comment]
Hi @PastaCoder,

Thanks so much for taking the time to contact us :+1:

If you wish to add the 1Password to your own `UIActivityViewController`, please take a look at the [ Adding the 1Password extension to a custom UIActivityViewController](https://gist.github.com/radazzouz/1f32eca216b1963dfc78) gist. Note that it the gist has a link to a [sample app](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20Browser%202.zip), **ACME Browser 2**. The sample code is in **Objective-C** and hope that it will give you an idea of how to implement it in **Swift**.

You must also note that this gist is a **pre-released** feature, meaning that it uses `-[OnePasswordExtension fillItemIntoWebView: forViewController: sender:showOnlyLogins:completion:` which is on master but not in the [1.2 release][https://github.com/AgileBits/onepassword-app-extension/releases/tag/1.2]. This also means that you must use `NO` for `showOnlyLogins:` so that other activities/extensions would show in the share sheet. And you must also wait for a new version of 1Password. This feature is not yet fully supported in the current App Store release of 1Password: You’ll see missing actions/extension in the share sheet with the current App Store version of 1Password.

> Should I always update my OnePasswordExtension.h and .m files as soon as you make changes? 

It’s really up to you, the stable releases are the tagged ones and [1.2][https://github.com/AgileBits/onepassword-app-extension/releases/tag/1.2] is the most recent one. We like to think of `master` as beta releases.

We strongly suggest that you thoroughly test your code before submitting your App to the App Store, should you choose to use `master` instead of tagged releases. You first question is the perfect example, the change is on master and not in [1.2][https://github.com/AgileBits/onepassword-app-extension/releases/tag/1.2].

Please let me know if you have any questions :-)

Cheers!


**P.S.** Let’s leave this issue opened so other developers can see it. We will close it as soon as the stable version of 1Password fully supports this feature.

**Comment by PastaCoder** [comment]
Hi Rad,
I'm facing some issues trying to use the code on the gist.

First and critical, I can't add UIActivityItemSource to my ViewController, since I get a "ViewController doesn't conform to UIActivityItemSource.
I also tried to use the code without the UIActivitySource functions, but it's still giving me a lot of different errors.

I'm using the master release.

What can I do?

Thanks :)

PastaCoder

**Comment by radazzouz** [comment]
Hi @PastaCoder,

In order to create a `UIActivityViewController` with the 1Password extension, you need to make your view controller conform to the `UIActivityItemSource` protocol and to implement its methods as shown in the gist. That's the only way to do it as far as we know.

Is there any particular reason why you can not do it?

Right now, with the current version of 1Password from the App Store, you won't be able to see all of the activities/extensions in the share sheet. You'll need our latest betas to fully test it. 

If you need beta access, please drop us a line at [support+appex@agilebits.com](mailto://support+appex@agilebits.com) with your Apple ID email address so we can add you to our TestFlight betas.

Hope that this helps :smiley: 

Best,

**Comment by PastaCoder** [comment]
Hi @radazzouz,

I sent you the email :)

To better explain the issue - I have my current `UIActivityViewController` set up on my main ViewController. These are the protocols used by the ViewController:
`class ViewController: UIViewController, UISearchBarDelegate, UIGestureRecognizerDelegate, WKNavigationDelegate {`
As you can see it doesn't include `UIActivityItemSource`. When I try to add the `UIActivityItemSource` to the ViewController it gives me the "does not conform error". This is the ViewController with the UIActivityItemSource:
`class ViewController: UIViewController, UISearchBarDelegate, UIGestureRecognizerDelegate, WKNavigationDelegate, UIActivityItemSource {` and this is the exact error: `Type 'ViewController' does not conform to protocol 'UIActivityItemSource'`.

Should I try adding the functions before I add it? or do you have any other suggestions?

Thanks,
PastaCoder

**Comment by PastaCoder** [comment]
Hi @radazzouz,
My idea to include the functions before adding the protocol to the ViewController worked. I will report further results soon.

Thanks,
PastaCoder

**Comment by PastaCoder** [comment]
Hi @radazzouz,
Sorry for the multiple replies :P
I'm stuck at this error now: `Binary operator '==' cannot be applied to operands of type '(String!) -> Bool' and 'String'` on the line
This is how I translated the `UIActivityItemSource` functions:
    
    func activityViewControllerPlaceholderItem(activityViewController: UIActivityViewController) -> AnyObject {
        return self._webView!.URL!

    }
    
    func activityViewController(activityViewController: UIActivityViewController, itemForActivityType activityType: String) -> AnyObject? {
        if OnePasswordExtension.sharedExtension().isOnePasswordExtensionActivityType == activityType {
            // Return the 1Password extension item
            return self.onePasswordExtensionItem
        } else {
            // Return the current URL
            return self._webView!.URL!
        }

    }
    
    func activityViewController(activityViewController: UIActivityViewController, dataTypeIdentifierForActivityType activityType: String?) -> String {
        // Because of our UTI declaration, this UTI now satisfies both the 1Password Extension and the usual NSURL for Share extensions.
        return "org.appextension.fill-browser-action"

    }

I tried using `if (OnePasswordExtension.sharedExtension().isOnePasswordExtensionActivityType == activityType) {` but got a different error: `Could not find an overload for '==' that accepts the supplied arguments`

Do you have any ideas how to fix this?

Thanks,
PastaCoder

**Comment by radazzouz** [comment]
Hey @PastaCoder,

No need to apologize for the multiple replies. It's awesome to see your train of thought. This will help me to better assist you :wink: 

Not being able to conform your view controller to the `UIActivityItemSource` protocol in Swift smells like a rdar to me. To be honest, I haven't tried this in Swift yet. So let's try and narrow this down...

* Do you see any error with the `Objective-C` [sample app](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20Browser%202.zip)?

* Can you please write a small sample app and send it to us? This will help us tremendously. This way we'll be able to _play_ with it too :wink: 

Thanks!

**Comment by PastaCoder** [comment]
Hi @radazzouz,
So, the view controller is now conformed, but another issue exists.

This is the code for UIActivityItemSource functions:

    func activityViewControllerPlaceholderItem(activityViewController: UIActivityViewController) -> AnyObject {
        return self._webView!.URL!

     }
    
     func activityViewController(activityViewController: UIActivityViewController, itemForActivityType activityType: String) -> AnyObject? {
        if OnePasswordExtension.sharedExtension().isOnePasswordExtensionActivityType(activityType) {
            // Return the 1Password extension item
            return self.onePasswordExtensionItem
        } else {
            // Return the current URL
            return self._webView!.URL!
        }

    }
    
     func activityViewController(activityViewController: UIActivityViewController, dataTypeIdentifierForActivityType activityType: String?) -> String {
        // Because of our UTI declaration, this UTI now satisfies both the 1Password Extension and the usual NSURL for Share extensions.
       return "org.appextension.fill-browser-action"

    }
This is the new share button code:

    @IBAction func _shareButton(sender: UIButton) {
        
        var onePasswordExtension: OnePasswordExtension = OnePasswordExtension.sharedExtension()
        onePasswordExtension.createExtensionItemForWebView(self._webView!, completion: { (extensionItem:NSExtensionItem!, error:NSError!) -> Void in
            
            if (extensionItem == nil) {
                NSLog("Failed to create an extension item: <%@>", error);
                return
            }
            self.onePasswordExtensionItem = extensionItem
            var activityItems = [self]
            })

            var activityItems = [self]
            var activityType:String!
            var completed:Bool
            var returnedItems:[AnyObject]!
            var activityError:NSError!
            
            let objectsToShare = [activityItems]
            let activityVC = UIActivityViewController(activityItems: objectsToShare, applicationActivities: nil)
            
            activityVC.completionWithItemsHandler = (activityType, completed, returnedItems, activityError) -> Void in
            if onePasswordExtension.isOnePasswordExtensionActivityType(activityType) {
                if (returnedItems.count > 0) {
                    onePasswordExtension.fillReturnedItems(returnedItems, self._webView!, completion: { (success:Bool, returnedItemsError:NSError) -> Void in
                        if (!success) {
                            NSLog("Failed to fill into webview: <%@>", returnedItemsError)
                        }
                    })
                }
            }
            
            if UIDevice.currentDevice().userInterfaceIdiom == .Pad {
                // The app is running on an iPad, so you have to wrap it in a UIPopOverController
                var popOver: UIPopoverController = UIPopoverController(contentViewController: activityVC)
                let rect = CGRect(origin: CGPoint(x: 559, y: 44), size: CGSize(width: 38, height: 32))
                // if your "share" button is a UIBarButtonItem
                popOver.presentPopoverFromRect(rect, inView: self.shareButton, permittedArrowDirections: UIPopoverArrowDirection.Right, animated: true)
                
            } else {
                self.presentViewController(activityVC, animated: true, completion: nil)
                
            }
    }

The errors are: `Consecutive statements on a line must be separated by ';'` and `Expected expression` on the completionHandlerWithItems line and `Cannot invoke 'fillReturnedItems' with an argument list of type '([AnyObject]!, WKWebView, completion: (Bool, NSError) -> Void)'` on the onePasswordExtension.fillReturnedItems line.

Can you see anything wrong?

P.S: I'm still working on the sample, this is from my own app.

Thanks,
PastaCoder

**Comment by radazzouz** [comment]
Hmm... this sounds like a Swift syntax error. I just Googled **"Consecutive statements on a line must be separated by ';'"** and most of the search results that I found seem to be referring to having an additional space somewhere in your code.

Hope that this helps :wink:

**Comment by PastaCoder** [comment]
Hi @radazzouz,
I got the new beta build :)
I also managed to solve the first errors, they occurred due to those pesky closures... I needed to use ({()}) instead of just ({}).

But now I'm left with the `Cannot invoke 'fillReturnedItems' with an argument list of type '([AnyObject]!, WKWebView, completion: (Bool, NSError) -> Void)'` on the onePasswordExtension.fillReturnedItems line. Can you try helping me find and fix the issue since it's using the onePasswordExtension class?

This is the code used for the completion handler with the fillReturnItems block:

    activityVC.completionWithItemsHandler = ({(activityType, completed, returnedItems, activityError) -> Void in
            if onePasswordExtension.isOnePasswordExtensionActivityType(activityType) {
              if (returnedItems.count > 0) {
               onePasswordExtension.fillReturnedItems(returnedItems, intoWebView: self._webView!, completion: ({(success:Bool, returnedItemsError:NSError) -> Void in
                      if (!success) {
                          NSLog("Failed to fill into webview: <%@>", returnedItemsError)
                      }
                  }))
               }
               }})

Thanks,
PastaCoder

**Comment by radazzouz** [comment]
Hey @PastaCoder,

I'm really glad to hear that you figured out the first issue!

Could you please send me a sample app so I can tinker with it on my end?

Thanks!

**Comment by radazzouz** [comment]
Hi @PastaCoder,

I just "translated" the sample app in Swift. You can download it [here](https://com-agilebits-users.s3.amazonaws.com/rad/Custom%20UIActivityViewController%20Swift.zip) and play with it if you like :wink: 

Also, here's the code that I use to create the `UIActivityViewController` with the 1Password extension in it

```objective-c
		// Create the 1Password extension item.
		onePasswordExtension.createExtensionItemForWebView(self.webView, completion: {(extensionItem, error) -> Void in
			if extensionItem == nil {
				println("Failed to create an extension item: <%@>", error)
				return
			}
			// Initialize the 1Password extension item property
			self.onePasswordExtensionItem = extensionItem

			var activityItems: NSArray = [ self ]; // Add as many custom activity items as you please

			// Setting up the activity view controller
			var activityViewController = UIActivityViewController(activityItems: activityItems as [AnyObject], applicationActivities: nil)

			if sender.isKindOfClass(UIBarButtonItem) {
				self.popoverPresentationController?.barButtonItem = sender as! UIBarButtonItem
			}
			else if sender.isKindOfClass(UIView) {
				self.popoverPresentationController?.sourceView = sender.superview
				self.popoverPresentationController?.sourceRect = sender.frame
			}

			activityViewController.completionWithItemsHandler = {(activityType, completed, returnedItems, activityError) -> Void in
				if onePasswordExtension.isOnePasswordExtensionActivityType(activityType) {
					if (returnedItems.count > 0) {
						onePasswordExtension.fillReturnedItems(returnedItems, intoWebView: self.webView, completion: { (success, returnedItemsError) -> Void in
							if success == false {
								println("Failed to fill login in webview: <%@>", returnedItemsError)
							}
						})
					}
					else {
						// Code for other custom activity types
					}
				}
			}

			self.presentViewController(activityViewController, animated: true, completion: nil)
		})
```

Hope that this helps :smile: 

Have a great weekend!

**Comment by PastaCoder** [comment]
Hi @radazzouz,

I managed to have working properly in my app now. There is just 1 tiny thing, on the Simulator, I can't see other extensions (The ones my app includes). On physical devices (both with the 1Password Beta, 1Password release build and without 1Password) everything works great. If the device has 1Password installed the extension is available and if 1Password isn't, the extension isn't available but the share sheet still appears and works great.

I finished translating the WebView Demo For iOS sample app from Objective-C to Swift and you can get it it [here](https://www.dropbox.com/s/fe1zi8p821b9suf/WebView%20Demo%20For%20iOS.zip?dl=0). It includes the code I used to create the Share Sheet with the 1Password Extension.

Thank you very much for everything! :)

Thanks,
PastaCoder

**Comment by radazzouz** [comment]
That's great news indeed!

I finished writing both demo apps (**ACME** and **ACME Browser**) in Swift. Please make sure that you take a look at issue #101 for my comments and at the [new/swift-demo-apps](https://github.com/AgileBits/onepassword-app-extension/tree/new/swift-demo-apps) branch for the code.

I will close this issue as resolved for now.

Best,

**Comment by PastaCoder** [comment]
Hi @radazzouz,

Nice :P

I worked on the translation of the app yesterday night and wanted to publish it today in the morning, but was only available now, but it seems you got ahead of me :P

For comparison, here is what I used for the Activity View Controller:
   
    @IBAction func fillUsing1PasswordExtension(sender: AnyObject) {
        
        var onePasswordExtension: OnePasswordExtension = OnePasswordExtension.sharedExtension()
        if self.webView!.URL != nil {
        // Create the 1Password extension item.
        onePasswordExtension.createExtensionItemForWebView(self.webView, completion: {(extensionItem:NSExtensionItem!, error:NSError!) -> Void in
            if (extensionItem == nil) {
                println("Failed to create an extension item: \(error)")
                return
            }
            // Initialize the 1Password extension item property
            self.onePasswordExtensionItem = extensionItem
            var activityItems = [self] // Add as many custom activity items as you please
            
            // Setting up the activity view controller

            var activityViewController:UIActivityViewController = UIActivityViewController(activityItems: activityItems, applicationActivities: nil)
            
            activityViewController.completionWithItemsHandler = ({(activityType, completed, returnedItems, activityError) in
                if onePasswordExtension.isOnePasswordExtensionActivityType(activityType) {
                    if (returnedItems.count > 0) {
                        onePasswordExtension.fillReturnedItems(returnedItems, intoWebView: self.webView, completion: ({(success, returnedItemsError) -> Void in
                            if (!success) {
                                println("Failed to fill into webview: \(returnedItemsError)")
                            }
                        }))
                    }
                }
            })
            if UIDevice.currentDevice().userInterfaceIdiom == .Pad {
                // The app is running on an iPad, so you have to wrap it in a UIPopOverController
                var popOver: UIPopoverController = UIPopoverController(contentViewController: activityViewController)
                let rect = CGRect(origin: CGPoint(x: 0, y: 0), size: CGSize(width: 38, height: 32))
                // if your "share" button is a UIBarButtonItem
                popOver.presentPopoverFromRect(rect, inView: self.onepasswordFillButton, permittedArrowDirections: UIPopoverArrowDirection.Any, animated: true)
            } else {
                self.presentViewController(activityViewController, animated: true, completion: nil)
            }
        })
        } else if self.webView!.URL == nil {
            println("Dispalying the Share Sheet failed because there is no URL loaded in the WebView.")
        }
    }

Have a terrific weekend! :)

Thanks for everything! :)
PastaCoder
