### ISSUE TITLE
1Password Extension shows Twitter and other services when retrieving login. [Fixed in the latest 1Password 5.5 betas]

### ISSUE THREAD

**Issue by renssies** [AgileBits/onepassword-app-extension#216]
Since iOS 8.3 the extension now also shows other services that accept URL's. Not sure if this is solvable by the extension or is just a iOS 8.3 bug. 

![img_4457](https://cloud.githubusercontent.com/assets/830094/7729525/95d5f0da-ff15-11e4-9a92-e7b1db09e728.jpg)

**Comment by radazzouz** [comment]
Hi @renssies,

Thanks for taking the time to write in :+1: 

This is not an App Extension API bug, it's a 1Password one. We are aware of this issue and we already fixed it in the latest 5.5 betas for iOS. So, I'll be closing this issue.

Cheers!

**Comment by noahemmet** [comment]
Hi! Does this mean apps using the existing 1Password extension won't have to update/re-submit to get access to this bug fix?

**Comment by radazzouz** [comment]
Hi @noahemmet, 

Exactly. You don't have to to make any changes or to resubmit your app. The fix is already in 1Password 5.5 betas.

As soon as we ship those fixes your app's share sheet will be fixed too :smile: 

Thanks!

**Comment by noahemmet** [comment]
Hi again! Could I please be added to the 5.5 beta list? Thanks!

**Comment by radazzouz** [comment]
Hi @noahemmet, 

Please drop us a line to support+appex@agilebits.com, along with a link to this issue.

Thanks!
