### ISSUE TITLE
isAppExtensionAvailable method doesn't work on iOS 9

### ISSUE THREAD

**Issue by c99koder** [AgileBits/onepassword-app-extension#231]
[[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:@"org-appextension-feature-password-management://"]]; always returns false, and the device console reports: 

<Notice>: -canOpenURL: failed for URL: "<CFURL 0x1766bad0 [0x368cfce8]>{string = org-appextension-feature-password-management://, encoding = 134217984, base = (null)}" - error: "<CFString 0x175a4f70 [0x368cfce8]>{contents = "This app is not allowed to query for scheme org-appextension-feature-password-management"}"

**Comment by radazzouz** [comment]
Hi @c99koder ,

Thanks for taking the time to reach out to us :+1:

I suppose that you’re only experiencing this issue on iOS 9 devices. Luckily there is a very easy way around it. Please make sure that you refer to the bottom of [ Use Case #1: Native App Login](https://github.com/AgileBits/onepassword-app-extension#use-case-1-native-app-login) of the README.

> **Important:** `isAppExtensionAvailable` uses `- [UIApplication canOpenURL:]`. Since iOS 9 it is recommended that you add the custom URL scheme, `org-appextension-feature-password-management`, in your target's `info.plist` as follows:

![](https://www.evernote.com/l/AVQvX8E3k-RFGaA-k2VnquPhoPI5V-zZby8B/image.png)

> For more information about URL schemes in iOS 9, please refer to the [Privacy and Your Apps session](https://developer.apple.com/videos/wwdc/2015/?id=703) from WWDC 2015 at around the the 9th minute mark.

Hope that this helps!

Have a great weekend!

**Comment by c99koder** [comment]
AH! Sorry, I missed that step when updating our app for iOS 9.  Thanks for the quick reply!

**Comment by radazzouz** [comment]
Hi @c99koder,

I am happy to hear that you've got it all sorted out :+1: 

If there's you have any other question, please do not hesitate to ask.

Enjoy your Saturday :wink:

**Comment by Uk44** [comment]
I set > org-appextension-feature-password-management in LSApplicationQueriesSchemes of Info.plist
still getting issue.
-canOpenURL: failed for URL: "org-appextension-feature-password-management:/ - error: "(null)"
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: ec1d1a7c2809c, ec1d1a7c2809c [live, PayPal iOS SDK 2.14.1]

**Comment by radazzouz** [comment]
Hi @Uk44 ,

Thanks for taking the time to write in!

Without a full picture of your project's settings it's a bit hard to diagnose this issue. In any case, let's try the following steps to try and solve it.

1. Can you recreate the issue in our demo apps?
2. Does the issue occur on a physical device or in the simulator? Is 1Password installed on the device in question?
3. From the log that you sent us, am I right in assuming that you added the 1Password API to the PayPal iOS SDK and not an actual app? If so, please note that you need to whitelist the `"org-appextension-feature-password-management"` scheme in your app's `info.plist` and not in an SDK/framework `info.plist`
4. Where are you calling `isAppExtensionAvailable`? Is it being called on the main thread? Why are you having payment errors logged at the same time? Please note that `isAppExtensionAvailable`'s only purpose is to determine if 1Password is installed.
5. What is your app's project settings? Base SDK, Deployment Target, etc.?
6. What is your setup? Version of iOS, Xcode, etc.

I look forward to your reply.

Have an amazing weekend!

**Comment by radazzouz** [comment]
It's been well over a month without any updates from the author. I assume that the issue is sorted out. If this is not the case, please send us over the info requested in my previous comment and I'll resume the investigation.

Thanks!
