### ISSUE TITLE
Feature Request: OSX support

### ISSUE THREAD

**Issue by corydolphin** [AgileBits/onepassword-app-extension#232]
As a user, I love 1Password integration in iOS apps (e.g Hipchat). I would love to see something similar made possible on OSX! Note: I have not dug in to how this works technically to understand if it is possible, so please feel free to tell me I'm crazy :-)

**Comment by radazzouz** [comment]
Thanks for taking the time to write in, @corydolphin :+1:

The **1Password App Extension API** for iOS is heavily based on the [NSItemProvider](https://developer.apple.com/library/prerelease/ios/documentation/Foundation/Reference/NSItemProvider_Class/index.html#//apple_ref/doc/uid/TP40014351), [NSExtensionItem](https://developer.apple.com/library/prerelease/ios/documentation/Foundation/Reference/NSExtensionItem_Class/index.html#//apple_ref/doc/uid/TP40014375), and [UIActivityViewController](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIActivityViewController_Class/index.html#//apple_ref/doc/uid/TP40011976)  APIs provided by Apple. They ensure a very convenient and secure way for your iOS app to comminicate to the 1Password extension thanks to the `UIActivityViewController` 's [completionWithItemsHandler](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIActivityViewController_Class/index.html#//apple_ref/occ/instp/UIActivityViewController/completionWithItemsHandler), which is not present in the current Mac APIs.

This means that we can't rely on these Awesome Apple APIs for a 1Password API for the Mac. We'd have to write it from scratch ourselves. This is definitely something that we are considering and we want to make sure that our Mac API would be as simple and convenient to integrate as our iOS API. We also need to make sure that  this said Mac API is Mac App Store/sandbox friendly.

Hope that this helps :smiley:

Have an amazing weekend!
