### ISSUE TITLE
Compiler compatibility issues

### ISSUE THREAD

**Issue by AriX** [AgileBits/onepassword-app-extension#233]
OnePasswordExtension.h includes "NS_ASSUME_NONNULL_BEGIN", a macro only defined in the iOS 8.3 SDK and later. There should be a __has_feature(nullability) check around this macro, or support for SDKs less than iOS 8.3 should be officially dropped.

Note that OnePassword.m is littered with declarations like #ifdef __IPHONE_8_0, which will always evaluate to true if the iOS 8.3 SDK is required to compile this file. It seems highly unlikely that one would build OnePassword.m with an SDK older than iOS 8, considering that Apple doesn't accept app submissions built with an SDK older than iOS 8, and this SDK is not very useful with extension support disabled, so it may be worth dropping support for the iOS 7 SDK (iOS 7 as a deployment target would, of course, still be supported).

**Comment by radazzouz** [comment]
Hi @AriX,

Thanks for taking the time to report this issue :+1:

There are no plans to drop the compatibility support for iOS 8.3 or earlier. There are so many apps out there that have the 1Password integration and that support iOS 7.

We recommend that the 1Password App Extension API is to be used with the latest stable version of Xcode  (see the [README](https://github.com/AgileBits/onepassword-app-extension#step-2-install-the-latest-versions-of-1password--xcode)). However, I think that it is good practice to use `#if __has_feature(nullability)`, so I PR’d the changes in PR #234. I tested it with Xcode 6.2 and it works fine.

Cheers!

**Comment by AriX** [comment]
Great, thanks!

**Comment by radazzouz** [comment]
:+1:
