### ISSUE TITLE
Accessing 1Password.xcassets from Cocoapods in code when frameworks are used

### ISSUE THREAD

**Issue by codywinton** [AgileBits/onepassword-app-extension#236]
I'm using 1Password via Cocoapods and I have `use_frameworks!` set in my Pod file. I'm using Swift.

I can access the images in my Storyboard, but it doesn't show up when the app is running. Also, when I try to access the images in code like such: `UIImage(named: "onepassword-navbar")` the image fails to load.

What am I doing wrong?

**Comment by tapi** [comment]
Because you are using frameworks the images are in a different bundle and `UIImage(named:  String)` only searches the main bundle. 
If you use `UIImage(named: String, inBundle: NSBundle?, compatibleWithTraitCollection: UITraitCollection?)` it should work  😀

**Comment by codywinton** [comment]
@tapi - That makes sense. What bundle am I looking for?

**Comment by tapi** [comment]
Typicaly I cheat and just use `NSBundle(forClass: AnyClass)` with a class I know is in the same bundle, so in this case you probably want to use `OnePasswordExtension.self` (Might be `OnePasswordExtension.Type` I have trouble keeping them straight)

**Comment by codywinton** [comment]
That solved it. Thanks!

**Comment by radazzouz** [comment]
@codywinton, I am really happy to hear that you've sorted it out :wink: 

@tapi, thanks so much for helping out! :+1: 

In a way this this a duplicate of #187, there are instructions in there spread across several comments, therefore I am adding this [sample project](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20Swift%20CocoaPods%20use_frameworks!.zip) illustrating how to use `use_frameworks!` with CocoaPods and Swift 1.2.

I hope that this will help other developers too :wink:

Best,
