### ISSUE TITLE
AppExtensionURLStringKey mentioned only once in README?

### ISSUE THREAD

**Issue by pwightman** [AgileBits/onepassword-app-extension#253]
From the README:

> An important thing to notice is the AppExtensionURLStringKey is set to the exact same value we used in the login scenario. This allows users to quickly find the login they saved for your app the next time they need to sign in.

That key is not used in any of the example code. Perhaps it was once used, but no longer? Maybe it should be added back or that paragraph changed to not refer to it anymore?

**Comment by radazzouz** [comment]
Good catch @pwightman :+1: 

`AppExtensionURLStringKey` is a constant used internally in `OnePasswordExtension`. It represents the dictionary key for the URL string we use find and store logins. However, in this context (the README), it makes more sense to refer to the `URLString` instead.

I just PR'd the changes in #254 to address it :wink: 

Cheers!

**Comment by telkomsel13** [comment]
#1
