### ISSUE TITLE
document.com_agilebits_onepassword_fill( raw_data ) is danger in some case

### ISSUE THREAD

**Issue by mala** [AgileBits/onepassword-app-extension#260]
How to reproduce

1. save password or create new login entry on 1password app
2. change url to attacker’s domain.
3. fillin password on malicious page by 1password app or extension.
4. nakedDomains contains original domain.

example: 
```
Object.defineProperty(document, "com_agilebits_onepassword_fill", {
	enumerable: false,            
	configurable: false,        
	writable: false,          
	value: function(a){       
		alert(JSON.stringify(a));
	}                         
});                     
```                                   
![op_screenshot](https://cloud.githubusercontent.com/assets/51196/9924518/1080b22e-5d3b-11e5-9b8e-b0c94c160daa.jpg)

- attacker can find another domain that is a target user using same password. 
- sub.example.com can get password-saved-domain.example.com (heroku, appspot, etc)

it is problem of js context. 
js context of “stringByEvaluatingJavaScriptFromString” is like a bookmarklet.

I also tested on browser extension(chrome,firefox), content script of browser extension run at “isolated world”  so browser extensions are maybe not affected.(I'm not investigating deeply)

**Comment by radazzouz** [comment]
Hello @mala,

Thanks for taking the time to write in for reporting this issue :+1:

The issue that you discovered is in fact made out of two issues:

* The issue where a malicious web page could pre-define `com_agilebits_onepassword_fill`.

* The issue where we send an array of all the `nakedDomains` of the selected item, which would affect users who save multiple and unrelated URLs for the same 1Password Login.

We’ve identified the fixes and are currently testing them in development. We’ll be sure to update you by commenting on this issue, and close it once the fix is out.

Cheers!

**Comment by mala** [comment]
@radazzouz @jxpx777 

Hi, I think that defense on js side is meaningless, because there are other ways to get js arguments.
https://github.com/AgileBits/onepassword-app-extension/pull/261

It would be better to use a local variables. (if there are no reasons to use document's property)
and raw_data to minimum data for fillin script.

```
(function(a){
 var fillin = function(){ ... }
 ...
 fillin();
})(stripped_data_for_fillin_script)

**Comment by jxpx777** [comment]
Thanks so much, @mala! It took @radazzouz and me the better part of today fighting with our build process but I think we have a good solution. I've updated #261 with the latest changes. I would love if you could take a look and let us know your thoughts.

**Comment by mala** [comment]
@jxpx777 
Hi, LGTM about js code. limitation of sending data is 1password app side?
I can't find limitation code, so please review it by your team.

Thanks.

**Comment by jxpx777** [comment]
Yes, that's right. On iOS, the domains list is handled by the app and not the JS. We can let you know when this is released so you can test further if you like. 

--
Jamie Phelps
Code Wrangler @ AgileBits

**Comment by mala** [comment]
ok, savedUrl and url also should be restricted, please take care.

**Comment by jxpx777** [comment]
The 'url' parameter only reflects the current page, so there's no privacy concern there. The savedURL parameter we can remove and I'm making that change now. Thanks for your feedback!

**Comment by radazzouz** [comment]
Thanks @mala! We are no longer sending the properties you mentioned (`nakedDomains`, `url` and `savedUrl`) in 1Password `6.0.1`. Please make sure that you check for updates in the App Store :+1: 

Once again, thank you so much for the assist here!
