### ISSUE TITLE
Documentation for web view filling method doesn't make sense

### ISSUE THREAD

**Issue by tijoinc** [AgileBits/onepassword-app-extension#262]
The header documentation for `-fillItemIntoWebView:forViewController:sender:showOnlyLogins:completion:` has the wrong set of parameters, seems it's the documentation for another method.

**Comment by radazzouz** [comment]
Nice catch @tijoinc !
Thanks so much for reporting this issue :+1: 

It's always good to know that developers read the docs.

I just PR'd the change in PR #263.

Cheers!
