### ISSUE TITLE
Adding org-appextension-feature-password-management to LSApplicationQueriesSchemes seems to break isAppExtensionAvailable checks

### ISSUE THREAD

**Issue by msepcot** [AgileBits/onepassword-app-extension#266]
Looks like this might be an Apple bug, but after adding org-appextension-feature-password-management to LSApplicationQueriesSchemes all calls to [[OnePasswordExtension sharedExtension] isAppExtensionAvailable] return YES, if I have 1Password installed or not.

**Comment by radazzouz** [comment]
Hi @msepcot,

Thanks for taking the time to write in.

Is it possible that you have another app installed which uses `org-appextension-feature-password-management` as URL scheme?

Cheers!

**Comment by msepcot** [comment]
Nope. I can even verify it in a clean simulator with the demo app. Remove the URL scheme and I see the alert window, with the URL scheme, no alert.

**Comment by radazzouz** [comment]
That’s very odd @msepcot ... I don’t seem to be able to reproduce it here. Can you please confirm that you have the same setup and that you followed the same steps as I did?

* Pulled the App Extension API from master (latest commit:[46ea0d8adb8150303f154366b19671d89dcd58d1](https://github.com/AgileBits/onepassword-app-extension/commit/cbd539d5bb14386c7a66fe165c7926ad269f41b8)) with no local changes.
* Built and ran any of the four demo apps using Xcode 7.0 (7A220) from the Mac App Store on a freshly reset simulator (iPhone 6 running iOS 9).
* As a result I get the alert. Meaning that `[[OnePasswordExtension sharedExtension] isAppExtensionAvailable]` returns `NO` when 1Password is not installed.

![](https://www.evernote.com/l/AVSTZD5mjNBJx6kbhfYYuVwk2iwnCRHQEKAB/image.png)

Am I missing something?

Best,

**Comment by msepcot** [comment]
Ah, user error. A teammate added the scheme to both CFBundleURLSchemes and LSApplicationQueriesSchemes, so everything is working as expected. Thought I had reset the simulator before trying the demo app, guess I didn't. Thanks for looking into this :-)

**Comment by radazzouz** [comment]
I'm glad that you've sorted it all out @msepcot :+1:
