### ISSUE TITLE
Ability to set "Username" label

### ISSUE THREAD

**Issue by benubois** [AgileBits/onepassword-app-extension#267]
Hi,

Love this extension. I have a feature request (maybe this is already implemented and I'm missing it?)

When calling 
```
storeLoginForURLString:loginDetails:passwordGenerationOptions:forViewController:sender:completion:
```
it would be great to have the option to customize the Username field label and placeholder text.

For an integration I'm working on I only want an email address back so I think it would be helpful to reinforce this with the language in the 1Password sheet and not have to only rely on validation. 

I'm guessing it might not be good to just make this a string, but if it was customizable with a couple of options i.e. either `Username` or `Email` that would be great.

![1](https://cloud.githubusercontent.com/assets/133809/10354310/c7504d7e-6d13-11e5-814c-1b7038d851e3.jpg)

**Comment by radazzouz** [comment]
Hi @benubois,

Thanks for taking the time to write in :+1: 

The ability to change "Username" with "Email" has previously been requested in issue #118. You can take a look at its discussion.

The "Username" field of a 1Password Login is a bit special: All 1Password Logins must have a "Username" field. Notice that this field is read-only and can not be edited (1Password for Mac, Windows and Android too). This field's **designation** is to fill its value into the username or email fields of webpages in the App Extension, Safari extension, 1Browser and all the supported desktop browsers.

I am therefore marking this issue as a duplicate and will close it for now.

Cheers!
