### ISSUE TITLE
isAppExtensionAvailable returns NO even if 1Password is installed

### ISSUE THREAD

**Issue by joelcarranza** [agilebits/onepassword-app-extension#27]
I am able to run extension successfully but:

```
[[OnePasswordExtension sharedExtension] isAppExtensionAvailable]
```

Always returns NO. It is returning NO for:

```
[[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:@"org-appextension-feature-password-management://"]]
```

I have 4.6b8 installed.

**Comment by thewhitewood** [comment]
For IOS9... 
<img width="619" alt="screen shot 2016-04-28 at 15 21 27" src="https://cloud.githubusercontent.com/assets/685229/14889029/f03ef88e-0d54-11e6-9be0-5c5af2fe9d34.png">

**Comment by radazzouz** [comment]
Hi @thewhitewood,

Yes indeed. You can find this information in the [README](https://github.com/AgileBits/onepassword-app-extension#use-case-1-native-app-login).

Best,
