### ISSUE TITLE
URLString should support wildcards

### ISSUE THREAD

**Issue by schluete** [AgileBits/onepassword-app-extension#275]
Our service uses a bunch of top-level domains on the web: `https://footer.com`, `https://foobar.de`, `https://foobar.co.uk` and so one. A new user to the app might have already saved a login for one of the websites in 1Password, but the app can't know which domain the user accessed on the web, thus being unable to pass a matching URLString when calling `findLoginForURLString:forViewController:sender:completion:`. 

It should be possible to pass a wildcard URL filter like `https://foobar.*` to the extension. This way the user would be shown all logins from the various possible top level domains.

**Comment by radazzouz** [comment]
Hi @schluete,

Thanks for taking the time to explain your requirements :+1: 

The 1Password App Extension, 1Browser and the 1Password for Mac all use [publicsuffix.org](https://publicsuffix.org) for matching logins (domain transformation). This topic has previously been raised in issue #131 and it's related issues (#87, #90, #115). Several solutions were proposed, including regex (wildcard) to address this issue. We ended up coming up with the "Show all Logins" solution (see the discussion in #131).

I am therefore, closing this issue as a duplicate.

Please let me know if you have any other questions.

Cheers!
