### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by lialios** [AgileBits/onepassword-app-extension#282]
Hello

When I add the libraries in a new xcode project, everything is ok.
The example apps in the download also work ok.

But when I try to add the libraries in the project that I am interested in adding the 1password integration, build fails with this:

ld: warning: directory not found for option '-L/Users/lialios/Documents/xcode/temp4/iphone-app/Hierarchy.Viewer.1.4.7'
Undefined symbols for architecture x86_64:
  "_kUTTypePropertyList", referenced from:
      -[OnePasswordExtension processExtensionItem:completion:] in OnePasswordExtension.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

What do I need to change in my project to make it work?

Thanks
Dionisis

**Comment by radazzouz** [comment]
Hi @lialios,

It’s a bit difficult to debug this issue at first glance. So I will list the potential suspects below:

* Make sure that you pulled or cloned the latest version of the App Extension API from master of from the `1.6.4` tag.
* Make sure that you are using the latest version of Xcode from the Mac App Store.
* Make sure that your project's **Base SDK** is iOS 8.0 or later.
* Make sure that you take the necessary precautions (imports) if your [**Deployment Target** is iOS 7.1 or earlier](https://github.com/AgileBits/onepassword-app-extension#projects-supporting-ios-71-and-earlier).

My the looks of it you are missing an import (`MobileCoreServices`). I can reproduce a similar build error in **ACME**, our demo app, if I comment out [`#import <MobileCoreServices/MobileCoreServices.h>`](https://github.com/AgileBits/onepassword-app-extension/blob/master/OnePasswordExtension.h#L10).

Please let us know if this helps :wink:

**Comment by lialios** [comment]
You are right!! The MobileCoreServices framework was missing, since my project didn't need it (until now)! Now the projects builds ok and I will continue with the implementation. Hopefully, my next request would be one to be included in the list of apps that have implemented 1Password.

Thank you so much, it was driving me crazy!

**Comment by radazzouz** [comment]
That is Awesome, @lialios !

I am really happy to hear that you've sorted it all out!

Yes please make sure that you give us shout at https://blog.agilebits.com/contact-developers/ to submit your app to our ["Apps ❤ 1Password" page](https://blog.agilebits.com/1password-apps/).

I will close this issue as `done` then.

Cheers!
