### ISSUE TITLE
Get number of Logins from 1Password extension

### ISSUE THREAD

**Issue by gianpispi** [AgileBits/onepassword-app-extension#287]
Hi!

Can I get, when I run the action "findLoginForURLString", the numbers of a site's login?
If this number is 0, I can run the action for add the login in 1Password.

Thanks in advance, 

Gianpiero

**Comment by radazzouz** [comment]
Hi Gianpiero,

Thank you for taking the time to write in :+1:

Your app can not "communicate" with the 1Password extension prior to calling it via the share sheet. Which means that there is no way to know in advance whether or not the user has matching Logins stored in 1Password.

I am pretty sure that you are requesting the ability to save a new Login in 1Password if no matching logins are found (see #107). I am therefore adding your vote to it and closing this issue as duplicate.

Have an Awesome weekend :wink:

Cheers!

Rad

**Comment by gianpispi** [comment]
Thank you very much! 

Merry Christmas!

Cheers,

Gianpiero

**Comment by radazzouz** [comment]
Cheers Gianpiero and Merry Christmas!🎄
