### ISSUE TITLE
Use passwordGenerationOptions to check manually entered pasword

### ISSUE THREAD

**Issue by lionel-alves** [AgileBits/onepassword-app-extension#291]
`passwordGenerationOptions` is really useful but it's too bad that if the user just enter a password manually 1Password doesn't check any of these options.
Would be great just to rename `passwordGenerationOptions` to `passwordOptions` and check these if the user tap a password manually (on top of using them for the password generation). Any chance this could happen?

Thanks!

**Comment by radazzouz** [comment]
Hi @lionel-alves,

Thanks for taking the time to write in :+1: 

> passwordGenerationOptions is really useful but it's too bad that if the user just enter a password manually 1Password doesn't check any of these options.

The password generation options _are_ taken into consideration if the user manually types the password. 

For example, if you build and run **ACME** and sign up, you will notice that the `!` and the `/` cannot be typed in the 1Password extension item detail view. See [the list of forbidden characters](https://github.com/AgileBits/onepassword-app-extension/blob/master/Demos/App%20Demo%20for%20iOS%20Swift/App%20Demo%20for%20iOS%20Swift/RegisterViewController.swift#L61) that it uses.

> Would be great just to rename passwordGenerationOptions to passwordOptions and check these if the user tap a password manually (on top of using them for the password generation). Any chance this could happen?

The options that the developer pass, are primarily intended to be used for the Password Generator. Renaming `passwordGenerationOptions` to `passwordOptions` may be misleading if not a confusing for some. We want to be as explicit as we can in this case.

For now I am closing this issue, but please do let me know if you have any other questions. 

All the Best!
