### ISSUE TITLE
Directions don't list MobileCoreServices.framework as a requirement

### ISSUE THREAD

**Issue by hborders** [AgileBits/onepassword-app-extension#294]
I added this project as a submodule and checked out the latest tag (`1.7`). Then, I added `OnePasswordExtension.h`, `OnePasswordExtension.m` and `1Password.xcassets`.

When I try to build, I see the following error:
```
Undefined symbols for architecture x86_64:
  "_kUTTypePropertyList", referenced from:
      -[OnePasswordExtension processExtensionItem:completion:] in OnePasswordExtension.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I worked around this by adding `MobileCoreServices.framework` to my `Link Binary with Libraries` build phase. I'm targeting iOS 7.1 and with an iOS 9.2 base SDK.

Please document that `MobileCoreServices.framework` is a required framework.

**Comment by radazzouz** [comment]
Hi @hborders,

Thanks for taking the time to write in and for integrating 1Password into your app.

This is already documented in the ["Projects supporting iOS 7.1 and earlier" section](https://github.com/AgileBits/onepassword-app-extension#projects-supporting-ios-71-and-earlier) of the README.

I am therefore closing this issue as `invalid`. Please let us know if this helps :wink:

All the Best!

**Comment by hborders** [comment]
The directions list `WebKit.framework` as a required framework. I was already including that. I see nothing about `MobileCoreServices.framework`.

**Comment by radazzouz** [comment]
@hborders, I just changed the deployment target to 7.1 for **ACME**, our sample app, and I got a compile error about the `WebKit.framework`, but not about `MobileCoreServices.framework`. Which version of Xcode are you using?

**Comment by hborders** [comment]
Version 7.2 (7C68)

**Comment by radazzouz** [comment]
Thanks for the quick follow up @hborders :+1: 

I tested **ACME** with iOS 7.1 as the Deployment Target and iOS 9.2 (latest) as the Base SDK as seen in this screenshot.

![](https://www.evernote.com/l/AVTd9p24XDVEiJDpcsxCWSFPlznTY7HtBRcB/image.png)

And it all works great! So I submitted PR #296 which should address your documentation issue.

Thanks so much!
