### ISSUE TITLE
Password Generation with more rules

### ISSUE THREAD

**Issue by omichde** [AgileBits/onepassword-app-extension#306]
Hi,
I could not find a solution to that so just asking wether I am missing something: can we enforce more rules while generating an account by 1Password, i.e. the need to have at least one uppercase character?

Thanks

**Comment by radazzouz** [comment]
Hi @omichde,

Thanks for taking the time to write in :+1: 

The password generator options or recipe are showcased in ACME's [RegisterViewController](https://github.com/AgileBits/onepassword-app-extension/blob/master/Demos/App%20Demo%20for%20iOS%20Swift/App%20Demo%20for%20iOS%20Swift/RegisterViewController.swift#L43).

By default when generating random passwords, the result will contain both lowercase and uppercase letters, therefore there is no need to "enforce" uppercase letters.

In any case, the user can still modify the generated password in while the 1Password extension. For example by choosing the wordlist password generator.

In the event that the 1Password extension returns a generated password which is not accepted by your backend, we recommend the following:

* Inform the user that the password could not be accepted and to show them the required recipe. 
* Prompt the user to update the password by calling [`changePasswordForLoginForURLString:`](https://github.com/AgileBits/onepassword-app-extension/blob/master/Demos/App%20Demo%20for%20iOS%20Swift/App%20Demo%20for%20iOS%20Swift/ChangePasswordViewController.swift#L27) to update the newly saved login.

You can achieve this by having a `isPasswordRejected` class property in your registration view controller.  The code should look as follows:

```
@IBAction func changePasswordIn1Password(sender:AnyObject) -> Void {
	if self.isPasswordRejected() {
		OnePasswordExtension.sharedExtension().changePasswordForLoginForURLString("https://www.mysite.com", loginDetails: newLoginDetails, passwordGenerationOptions: passwordGenerationOptions, forViewController: self, sender: sender) { (loginDictionary, error) -> Void in
			self.passwordRejected = validatePasswordWithTheBackEnd();
		}
	}
	else {
		OnePasswordExtension.sharedExtension().storeLoginForURLString("https://www.mysite.com", loginDetails: newLoginDetails, passwordGenerationOptions: passwordGenerationOptions, forViewController: self, sender: sender) { (loginDictionary, error) -> Void in
			self.passwordRejected = validatePasswordWithTheBackEnd();
		}
	}
}
```
I am closing this issue for now, but please feel free to continue the conversation in this issue. Please let me know if this helps :wink: 

Cheers!

**Comment by omichde** [comment]
Hi @radazzouz
this looks like the best way to go, thanks many times for this tip, will try that on monday!
Cheers...

**Comment by radazzouz** [comment]
That is great to hear, @omichde! Thanks for getting back to me so quickly :+1: 

This issue made me open issue #307. I think that the solution described in previous comment should make it into our [Wiki](https://github.com/AgileBits/onepassword-app-extension/wiki). This way, we hope to be used my more developers.

Please let me know how did work for you and also please do let me know if there's anything I can do for you after you try it out on Monday.

Have an Awesome weekend!

**Comment by omichde** [comment]
Hi @radazzouz,

by means of your code I could at least re-implement this feature in our APP, but due to the poor/disconnected APP extension API, I had a hard time arguing about it with our product owner. But this is not bound to 1P nor your extension - which is working fine so thanks again for your help.

Cheers, Oliver

**Comment by radazzouz** [comment]
Hi Oliver,

Thanks for getting back to us :+1: 

I am not sure I fully understand what you meant by **"poor/disconnected APP extension API"**. Is this something, we can improve on our end?

BTW, if you wish to move this conversation to a more private channel, please feel free to email us at support+appex@agilebits.com.

Best,

Rad

**Comment by omichde** [comment]
Hi Rad,

my concern is that our login screens are setup in a way where the user cannot easily update the (possibly changed) credentials afterwards - because he was moved to a different confirmation page, currently unaware of any credential handling.

And even if so, from a UX perspective, it's weird to ask the user on the confirmation page to store his credentials (again), selecting the 1P extension point, open the 1P extension (probably via TouchID) and confirm his changes.

Again, I know that this is due to the limited Extension API of UIKit.

Cheers, Oliver

**Comment by radazzouz** [comment]
Thanks again for taking the time to explain, Oliver!

Now that I understand how your app's login screens are setup, I totally agree with you. You are right about the Extension API not allowing a "session"-like method of communication between the host app (your app) and the 1Password extension.

From a UX perspective, I agree that it is weird to ask the user on the confirmation page to "update" their credentials again. In my previous [comment](https://github.com/AgileBits/onepassword-app-extension/issues/306#issuecomment-189404151), I was suggesting to add the ability to "allow" the user to update the credentials and not necessarily "ask".

Hope that this clarifies things a bit. Anyway, please do let us know if you have any other questions and make sure that you give us a heads up at https://blog.agilebits.com/contact-developers/ to submit your app to our ["Apps ❤ 1Password"]( https://blog.agilebits.com/1password-apps/ ).

All the Best,

Rad
