### ISSUE TITLE
Document the trick described in #306 which circumvents the unaccepted generated password in "storeLoginForURLString"

### ISSUE THREAD

**Issue by radazzouz** [agilebits/onepassword-app-extension#307]
In issue #306, @omichde raised a very good point. The workaround described in [my comment](https://github.com/AgileBits/onepassword-app-extension/issues/306#issuecomment-189404151) should be in our wiki.

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, I'm closing out any remaining issues and branches.
