### ISSUE TITLE
Making param sender nullable for iPad. Support for Cordova Plugin

### ISSUE THREAD

**Issue by Raphy1302** [AgileBits/onepassword-app-extension#310]
I've used this app extension for building an cordova plugin. (https://github.com/SPIRIT-21/cordova-plugin-1password ). This extension simply passes the functions available in your extension to a cordova plugin. The only issue I have with it is the requirement of a sender with an iPad. In an cordova plugin the functions are not an native iOS Event so I don't have any sender object. Is there any way you could make this param nullable or is there any workaround possible?

Kind regards
Raphael

**Comment by radazzouz** [comment]
Hi Raphael,

Thanks for taking the time to write in :+1: 

Sending a `nil` sender to `findLoginForURLString:` will crash the app when running it on iPad.

The method signature allows you to pass a `nil` sender.

```
- (void)findLoginForURLString:(non null NSString *)URLString forViewController:(non null UIViewController *)viewController sender:(nullable id)sender completion:(nullable void (^)(NSDictionary * __nullable loginDictionary, NSError * __nullable error))completion
```

However, even if you remove the [NSAssert from `OnePasswordExtension.m` line 507](https://github.com/AgileBits/onepassword-app-extension/blob/master/OnePasswordExtension.m#L507) from your fork, it will still crash on iPad, as the `UIActivityViewController` needs a non-nil `sourceView` and `sourceRect`.

I recommend that you try and send an instance of a `UIView` or even `self` (the current view controller).

Hope that this helps. I'll be closing this issue for now. Please feel free to join the conversion about Cordova support in issue #155.

Cheers!
