### ISSUE TITLE
Add the ability to pass options to `findLoginForURLString:`

### ISSUE THREAD

**Issue by radazzouz** [agilebits/onepassword-app-extension#312]
Users can now create new Logins if no matching logins were found.

![](https://www.evernote.com/l/AVSHLvk1yZxKqLf_eqg9CtWf6pN0GO2T6xkB/image.png)

We need to allow developers to pass options such as the password generator options, the item title, etc. when using `findLoginForURLString:`

**Comment by radazzouz** [comment]
<font size='1' color='grey'><i>ref: OPI-2722</i></font>

**Comment by wyllys66** [comment]
Also would be nice to hide fields such as the "Login" name for situations where the app or form does not need it.

**Comment by radazzouz** [comment]
Hi @wyllys66,

Hiding fields is beyond the scope of this feature and will create complications with 1Password on other platforms (Mac, Windows and Android)

A 1Password Login needs to have the username field, Without it, it wouldn't be a login it would be a password. We can't simply hide fields.

For your use-case, we recommend that you pass an empty space (@" ") for `AppExtensionUsernameKey` when this feature will be available.

Thanks for understanding.

**Comment by Charnarongthumwan** [comment]
Good

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, I'm closing out any remaining issues and branches.
