### ISSUE TITLE
Ignore partial-availability warnings in source

### ISSUE THREAD

**Issue by hborders** [AgileBits/onepassword-app-extension#313]
Xcode 7.3 introduced `-Wpartial-availability`, which causes warnings throughout a codebase that targets iOS7. Since you already guard your methods with appropriate `#ifdef`s, you should wrap all calls that require iOS8 or iOS9 thusly:

Compile-time:

```
#ifdef __IPHONE_8_0
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wpartial-availability"
        
// iOS8 or iOS9 specific code
        
#pragma clang diagnostic pop
#endif
```

Runtime:

```
if ([theObject respondsToSelector:@selector(theSelector)]) {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wpartial-availability"
        
// iOS8 or iOS9 specific code
        
#pragma clang diagnostic pop
}
```

**Comment by radazzouz** [comment]
Hi @hborders,

Thanks for taking the time to write in. :+1: 

> Xcode 7.3 introduced -Wpartial-availability, which causes warnings throughout a codebase that targets iOS7.

You mean base SDK iOS 8.0 or later and Deployment Target iOS 7.1 or later?

I just changed the Deployment Target to iOS 7.1 for ACME, our Objective-C demo app and I didn't see any warnings in Xcode 7.3. Am I missing something?

I look forward to your reply.

Cheers!

**Comment by hborders** [comment]
> You mean base SDK iOS 8.0 or later and Deployment Target iOS 7.1 or later?

This is the exact warning I see:

```
In file included from /onepassword-app-extension/OnePasswordExtension.m:8:
/onepassword-app-extension/OnePasswordExtension.h:194:80: warning: 'NSExtensionItem' is partial: introduced in iOS 8.0 [-Wpartial-availability]
- (void)createExtensionItemForWebView:(nonnull id)webView completion:(void (^)(NSExtensionItem * __nullable extensionItem, NSError * __nullable error))completion;
                                                                               ^
```

I have `-Weverything` enabled, so I'm probably seeing warnings that aren't enabled by default. It isn't essential that you fix this because I can disable the warnings manually in my project file, but it would certainly be nice if they were disabled in source (or in your `Podfile`, though that would only help CocoaPods users).

**Comment by radazzouz** [comment]
Thanks for getting back to me so quickly, @hborders :+1: 

Now I see. I didn't have `-Weverything` enabled. I now fully understand your request and I see where you're coming from, however wrapping the entire iOS 8 and 9 only code in `#pragma clang diagnostic` doesn't really make sense, as this whole API targets iOS 8 later.

For your specific case, I suggest to either do this in your source code or in a fork.

I am closing this issue as `won't do`.

If you have any other questions, please let us know.

All the Best,

**Comment by hborders** [comment]
Would you consider adding it just around

```
- (void)createExtensionItemForWebView:webView completion:(void (^)(NSExtensionItem * __nullable extensionItem, NSError * __nullable error))completion;
```

in `OnePasswordExtension.h`? I can't ignore warnings in header files.

**Comment by radazzouz** [comment]
Can't this be done in a fork of this repo?

**Comment by hborders** [comment]
It could be. I just thought this would be small enough to add. I totally understand why you don't want to support `-Weverything`. I'm not trying to be a pest, and if I am, I apologize.

**Comment by radazzouz** [comment]
No need to apologize, @hborders.

I wonder if we could get around this by using the framework version of the API. For more info checkout the sample projects from the [add-framework-support](https://github.com/AgileBits/onepassword-app-extension/tree/add-framework-support) branch.

Please let me know how it goes :smile:

**Comment by hborders** [comment]
We can't use frameworks yet because we must still support iOS7, and frameworks can [add startup time](https://github.com/artsy/eigen/issues/586) (though only 1 more framework probably isn't a big deal).

**Comment by hborders** [comment]
Actually, I figured out that I just needed to wrap the clang ignore pragmas around the one place in my code that imported the offending header file. I thought the header file warning detection was some magic Xcode was doing, but of course it wasn't because Xcode isn't magical. :)

**Comment by radazzouz** [comment]
Wait what? Xcode isn't magical? :stuck_out_tongue_winking_eye: 

Seriously now, I am really glad to hear that you've sorted it all out!

Cheers!
