### ISSUE TITLE
Cast from 'const struct __CFString *' to 'NSString *' drops const qualifier

### ISSUE THREAD

**Issue by hborders** [AgileBits/onepassword-app-extension#314]
I have `-Weverything` enabled, and I see the following `const` warnings in Xcode 7.3 now:

```
/onepassword-app-extension/OnePasswordExtension.m:475:72: warning: cast from 'const struct __CFString *' to 'NSString *' drops const qualifier [-Wcast-qual]
        if (NO == [itemProvider hasItemConformingToTypeIdentifier:(NSString *)kUTTypePropertyList]) {
                                                                              ^
/onepassword-app-extension/OnePasswordExtension.m:485:54: warning: cast from 'const struct __CFString *' to 'NSString *' drops const qualifier [-Wcast-qual]
        [itemProvider loadItemForTypeIdentifier:(NSString *)kUTTypePropertyList options:nil completionHandler:^(NSDictionary *itemDictionary, NSError *itemProviderError) {
                                                            ^
```

(Sorry for just throwing these over the wall rather than submitting a patch, but I have to go through legal review for any patch submission, and that's a big hassle for me.)

**Comment by radazzouz** [comment]
Thanks @hborders. No big deal, I totally understand. As I mentioned in #313, we are not going to support the `-Weverything` compiler flag, even if I totally understand your situation. This would render the code unreadable and unmaintainable.

I won't be closing this issue as `won't do` right now, but if you prefer we can take this somewhere more private (support+appex@agilebits.com).

And finally, would the DYI/fork approach be accepted by the legal review?

Please keep me posted.

**Comment by hborders** [comment]
I don't think my manager would consider it worth our time to review just to disable a few warnings. I'd probably fork it internally if I forked it at all. However, I'd rather not go through the struggle of maintaining the fork, so I'd probably just add the warnings to the list I ignore.

**Comment by radazzouz** [comment]
Hello again @hborders,

It all depends, on the API capability that you wish to use. For example `findLoginForURLString:` hasn't changed in a very longtime, but the collect and fill scripts used in `fillLoginIntoWebView:` change quite regularly. 

I hope that this will help you in making the decision :wink: 

Cheers!
