### ISSUE TITLE
Ability to modify the UIActivityViewController that is presented during -findLoginForURLString:

### ISSUE THREAD

**Issue by ksm** [AgileBits/onepassword-app-extension#315]
I use both Safari Saved Password and the 1Password app extension in my app. I would like both of these to show up after tapping on a single button.

The 1Password app extension instantiates, configures and presents a `UIActivityViewController` when `-findLoginForURLString:` is invoked. I'd love to be able to add the option to invoke Safari Saved Password in that activity view controller.

There's an app that already does this on the U.S. AppStore, the Simple banking app. Here's a screenshot (the twitter discussion there is somewhat related to this issue): https://twitter.com/karolsmazur/status/677911970159415297

**Comment by radazzouz** [comment]
Hi @ksm!

Thanks for taking the time to write in. :+1: 

This matter has previously been discussed in PR #308. I strongly recommend that you take a look at the discussion within.

What you wish to achieve can easily be implemented by forking this repo and applying the same changes from the aforementioned PR. Basically, you can add your custom `UIActivity` to the `UIActivityViewController` from `findLoginForURLString:`

I am closing this issue with the `duplicate` tag for now, but please feel free to ping me should you have additional questions.

Cheers!
