### ISSUE TITLE
Q: Possible to show share sheet with only 1PW extension from webview?

### ISSUE THREAD

**Issue by garvankeeley** [AgileBits/onepassword-app-extension#320]
Currently the fillItemIntoWebView() function will trigger a share sheet populated with all items. Is it possible to trigger share sheet from a webview that looks like this:
<img width="649" alt="screenshot 2016-03-30 10 36 02" src="https://cloud.githubusercontent.com/assets/5495083/14145819/448c9026-f663-11e5-8f80-e1739fdeca0c.png">

**Comment by radazzouz** [comment]
Hi @garvankeeley!

Thanks for taking the time to ask this question. :+1: 

Yes, it is possible. You simply need to pass `YES` (or `true`) for the `showOnlyLogins` parameter.

Let me know if this helps.

Cheers!

**Comment by garvankeeley** [comment]
Nice! Looks much better now.
Trying to add a specific 1PW button to our browser that is distinct from the existing Share menu button method, and their wouldn't be much point if both buttons brought up the exact same crowded share menu.

**Comment by radazzouz** [comment]
Thanks for getting back to me so quickly, @garvankeeley :+1: And for sharing with me your intensions.

If I may, I'd recommend against using a different 1Password button for your browser, as users are already accustomed to the 1Password extension showing up alongside other activities and extensions in the share sheet when using a browser (Safari, Chrome, Firefox, Brave, etc.).

Hope that this helps.

All the Best,
