### ISSUE TITLE
Carthage support with tag version

### ISSUE THREAD

**Issue by calvinlyc** [AgileBits/onepassword-app-extension#325]
We are recently integrating with onepassword extension with our app. We use the "add-framework-support" branch as our carthage dependency however we'd prefer to using tag rather than branch since tag can tell the version and we will be able to compare between different release notes.  Will it be possible to enable the support for the tags since the tag version complain about "Dependency "onepassword-app-extension" has no shared framework schemes"?  

Looking forward to your reply and thanks for your help

**Comment by radazzouz** [comment]
Thanks so much for taking the time to open this issue, @calvinlyc 👍 

This is indeed something that we've considering for a while now. It makes perfect sense to tag the framework branch too. So I just created the `framework/1.8.1` tag for the latest stable version (commit [b447f1e4b20463c1693ee1a093b01dc29cdb87b1](https://github.com/AgileBits/onepassword-app-extension/commit/b447f1e4b20463c1693ee1a093b01dc29cdb87b1)) from `add-framework-support` branch. Please let me know if it works for you.

In the meantime, I am closing this issue.

All the Best,
