### ISSUE TITLE
Oncepassword to show up in UIActivityViewController automatically

### ISSUE THREAD

**Issue by maxykato** [AgileBits/onepassword-app-extension#328]
Hi,

I recently found out that "Read it Later" selection automatically shows up in Activity menu on a 3rd party app after I installed Facebook app.

Can OnePassword do the same so that user can use OnePassword if s/he wants without a developerI implementing OnePassword extension on his/her app?

**Comment by radazzouz** [comment]
Hi @maxykato,

Thanks so much for taking the time to write in and for asking such a great question. :+1:

> Can OnePassword do the same so that user can use OnePassword if s/he wants without a developerI implementing OnePassword extension on his/her app?

Technically, it would be possible for us (AgileBits) to force the 1Password extension to show up in most share sheets (`UIActivityViewControllers`) without any intervention from third party developers. We could achieve this via [NSExtensionActivationRule key](https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW8) in our extension's `info.plist`. However, we chose not to do it for the following reasons:

* All of the App Extension API's capabilities, including [Web View Filling](https://github.com/AgileBits/onepassword-app-extension#use-case-4-web-view-filling) require the third party app (a.k.a the host app) to do the filling (see how it is done in [- [OnePasswordExtension executeFillScript: inWebView: completion:]](https://github.com/AgileBits/onepassword-app-extension/blob/master/OnePasswordExtension.m#L413)).
* We believe that showing the 1Password extension into all share sheets even when it (the extension) cannot perform filling is a bad user exterience for our users: Users expect the 1Password extension to work all the time.

I hope that this helps. I am closing this issue for now.

Have an amazing weekend!
