### ISSUE TITLE
new/ios10 branch doesn't include Carthage support

### ISSUE THREAD

**Issue by lvandal** [AgileBits/onepassword-app-extension#332]
Seems like the Xcode project is missing from this branch.

**Comment by radazzouz** [comment]
Hi @lvandal,

Thank you for taking a look at the new iOS 10 branch and for taking the time to writer in! 👍 

Just like on `master`, this branch has the main Xcode workspace (`1Password Extension Demos.xcworkspace`) located in [`onepassword-app-extension/Demos/`](https://github.com/AgileBits/onepassword-app-extension/tree/new/ios10/Demos) and an Xcode project (`.xcodeproj` file) located in each demo app's directory.

Which Xcode project file are you missing? Is it `OnePasswordExtension.xcodeproj`? If so, then please note that this Xcode project is only available in the [`add-framework-support`](https://github.com/AgileBits/onepassword-app-extension/tree/add-framework-support) branch.

I look forward to your reply!

Cheers!

**Comment by radazzouz** [comment]
Linking this issue to #329.

**Comment by lvandal** [comment]
I can simply copy the Xcode project file and Info.plist in order for Carthage to work with the `new/ios10` branch but I was wondering if at some point you'll either add the missing files or create a new branch for `add-framework-support`?

**Comment by radazzouz** [comment]
Thanks so much for the quick response, Luc!

We haven't started to work on iOS 10 + Carthage compatibility yet. We will very soon. We'll most likely branch from `add-framework-support` and rebase the changes from `new/ios10` to the new branch.

Please stay tuned! I'll comment on this issue when the new branch is ready!

Cheers!

**Comment by radazzouz** [comment]
I just published the [`new/carthage+ios10`](https://github.com/AgileBits/onepassword-app-extension/tree/new/carthage%2Bios10) branch for Carthage compatibility with Xcode 8 and Swift 3.

I am closing this issue as `duplicate`, so that we centralize discussions in #329.

@lvandal, please let me know if things work fine for you from the new branch.
