### ISSUE TITLE
UI Bug - Keyboard overlaps extension on iPad Portrait.

### ISSUE THREAD

**Issue by ay5000** [AgileBits/onepassword-app-extension#336]
Please see screenshot. The extension is still functional, but keyboard cuts off the bottom part.

![02](https://cloud.githubusercontent.com/assets/15784560/17119685/69b350d6-5295-11e6-84df-3c8a4813cd89.png)

**Comment by radazzouz** [comment]
Hello again @ay5000,

And once again thanks so much for reporting this issue and #337.

At the risk of sounding redundant, this issue just like #337 is also an internal bug that we are aware of (OPI-3436).

So this is not an App Extension API issue and this issue does not belong to this repository. I am closing it for now and adding your concern to our internal issue.

Please let me know if there's anything else I can do to help.

All the Best,

<font size='1' color='grey'><i>ref: OPI-3436</i></font>
