### ISSUE TITLE
UI Bug - Keyboard overlaps extension on iPad Landscape and unlock button doesn't work.

### ISSUE THREAD

**Issue by ay5000** [AgileBits/onepassword-app-extension#337]
Please see screenshot. Similar to @https://github.com/AgileBits/onepassword-app-extension/issues/336 but here the keyboard overlaps on landscape. In addition the unlock button doesn't work (have to press Go on keyboard to use the extension. 

![01](https://cloud.githubusercontent.com/assets/15784560/17119712/9ef8ada4-5295-11e6-8415-2d35d48e7519.png)

**Comment by radazzouz** [comment]
Hi @ay5000,

Thanks for taking the time to write in! 👍 

We are aware of this issue and we already have an internal bug (OPI-3309) filed in our issue tracker.

Note that this is not an App Extension API issue, therefore this issue does not belong to this repository. I am closing it for now and adding your concern to our internal issue.

Hope that this helps. I will be addressing #336 separately.

Cheers!

<font size='1' color='grey'><i>ref: OPI-3309</i></font>
