### ISSUE TITLE
Expose, or add ability to provide a adaptivity delegate

### ISSUE THREAD

**Issue by haxie1** [AgileBits/onepassword-app-extension#344]
The extension presents UIActivityViewController on a view controller that we pass in. However, there is no way to add a popoverPresentationController.delegate to this controller prior to presentation which causes the activity popover to get misplaced on device rotation and makes it difficult to handle adaptivity of the presented controller. Could you expose the activity controller, or provide a way to set this delegate so we can handle adaptivity of the popover correctly?

**Comment by radazzouz** [comment]
Thanks so much for taking the time to write in, @haxie1! 👍

Please make sure that you take a look at our **Adding the 1Password extension to a custom UIActivityViewController** [wiki page](https://github.com/AgileBits/onepassword-app-extension/wiki/Adding-the-1Password-extension-to-a-custom-UIActivityViewController). Please let me know if this helps.

For now, I am closing this issue and labeling it as `question`.

Cheers!

**Comment by haxie1** [comment]
Thanks for the response,

We are using the findLoginForURLString:... scenario, but from reading the wiki page you linked, it appears that it is for use with the web view filing scenario? Will this work for our scenario too?

**Comment by radazzouz** [comment]
Thanks for getting back to me, @haxie1!

No, the [Wiki article](https://github.com/AgileBits/onepassword-app-extension/wiki/Adding-the-1Password-extension-to-a-custom-UIActivityViewController) from my previous comment is indeed only valid for the web view filing scenario and not for `findLoginForURLString:`. When using the latter, the user shouldn't be able to use the share sheet for anything other than logging in using a password manager. The user does not usually want to share the URL or post it on a social network.

In any case, could you please tell me more about your use-case? If you prefer doing this in a non-public fashion, feel free to drop me a line at support+appex@agilebits.com.

I look forward to your reply!

Cheers!
