### ISSUE TITLE
ONE_PASSWORD_EXTENSION_ENABLE_WK_WEB_VIEW define doesn't work if connected as CocoaPod

### ISSUE THREAD

**Issue by rermolov** [AgileBits/onepassword-app-extension#362]
What I do:
1) Create new project with deployment target < 8.0
2) Add 1PasswordExtension through CocoaPods
3) Open .xcworkspace
4) Set ONE_PASSWORD_EXTENSION_ENABLE_WK_WEB_VIEW=1 in my project/target settings (doesn't matter)
5) Build project

What I receive:
WKWebView-dependent code is not compiled in OnePasswordExtension.m.

What I expect:
WKWebView-dependent code should compile.

Reason:
Defines in my target doesn't affect defines in .m files of Pods targets.

**Comment by gks** [comment]
Hi @rermolov 

Sorry for the delay on getting back to you on this one. 

Could you tell me a bit more about what you're trying to do exactly and what your environment for the application you're working on looks like?

The idea behind the ONE_PASSWORD_EXTENSION_ENABLE_WK_WEB_VIEW setting is to allow for the developer of the app to control the runtime checking, but the code will only get compiled on iOS 8 and later targets. That code simply won't run on iOS 7.1 or earlier so you wouldn't want it to be run on a device that is running on those iOS versions. You'd only want it to run on iOS 8 devices and later. I assume in your case that your testing of this was on a device that was earlier than iOS 8.0. 

But if you could please tell me a bit more about what you're trying to accomplish I might be able to help you figure out the best path forward.

**Comment by gks** [comment]
I'm closing this issue for now, if you're still having difficulty please write back in, but it has been over a month since last contact.
