### ISSUE TITLE
iOS10 crashes on iPhone when calling findLoginForURLString

### ISSUE THREAD

**Issue by ehlersd** [AgileBits/onepassword-app-extension#368]
It crashes when calling the presentViewController for the activityViewController in the above function (findLoginForURLString:forViewController:sender:completion:).

I send sender to nil just to confirm that it wasn't the problem.

Not quite sure how to debug this further, looking for ideas where to look.

The iOS activity view never displays...

**Comment by ehlersd** [comment]
Crap, nevermind.  It appears to be using a UIView and not a UIViewController for this app.  I'll correct that and report back if there is a further problem.

**Comment by gks** [comment]
@ehlersd Glad to hear you got it working :)

Sorry about the trouble though. If we can ever assist at all just reach out.
