### ISSUE TITLE
Add license to OnePasswordExtension.h & OnePasswordExtension.m

### ISSUE THREAD

**Issue by tdmalone** [agilebits/onepassword-app-extension#369]
Both these files state copyright with all rights reserved, which makes their use troublesome for diligent users:

* https://raw.githubusercontent.com/AgileBits/onepassword-app-extension/master/OnePasswordExtension.h
* https://raw.githubusercontent.com/AgileBits/onepassword-app-extension/master/OnePasswordExtension.m

I note this repo is MIT licensed; could you please reflect that fact in the header of the above files (and others if appropriate - these are the only ones I've looked at so far).

Thank you!

**Comment by rudyrichter** [comment]
resolved by #417
