### ISSUE TITLE
https://www.spotify.com/opensource/plain/https://github.com/agilebits/onepassword-app-extension

### ISSUE THREAD

**Issue by ethanhunt88** [agilebits/onepassword-app-extension#375]
Problem on Spotify 

Security is OPEN

**Comment by gks** [comment]
Hi @ethanhunt88 

I'm sorry to hear you're having difficulty. Could you be a little more specific about the problem you're encountering? The more details you can provide me the better I might be able to assist.

You provided two links in the title of the bug report, one for Spotify which links off to various open source projects they use, notably Chromium. The other a direct link to this exact repository.

Unfortunately neither gives me a great deal of insight into what issue you're encountering. Any additional information you can give me to help me help you would be greatly appreciated.
