### ISSUE TITLE
Not filling webview fields

### ISSUE THREAD

**Issue by cristiangoncas** [agilebits/onepassword-app-extension#376]
Hello, 
I'm working on a webview app using webkit and integrating onepassword.
The issue is when I select the account to use, the webview is reloaded and I'm getting a true on completion but the log in is not happening.
I'm not using a button to open onepassword, I'm using an event from the webview.
Here is the code what I'm executing and is returning true.

```
OnePasswordExtension.shared().fillItem(intoWebView: webView, for: self, sender: nil, showOnlyLogins: false) { (success, error) -> Void in
                if success == false {
                    print("Failed to fill into webview: <\(error)>")
                }
}
```

I hope someone can help me.

Thank you

**Comment by gks** [comment]
Hi @cristiangoncas I was just investigating this and noticed you closed the issue.

Were you by chance able to get things figured out?

**Comment by cristiangoncas** [comment]
Hi @gks 
I'm sorry, I forgot to write the issue.
It was working right, but I discovered a bug because of this.

Thanks for your response

**Comment by gks** [comment]
Understood, @cristiangoncas, as long as things are working properly that's what matters on our end. If we can provide any assistance please let us know. Thanks for implementing 1Password support in your app!

When you have implemented support and it's available to users please be sure to email us: support+appex@agilebits.com

Include your apps icon and a brief description so we can get it included on our page that highlights [apps that feature 1Password support](https://blog.agilebits.com/1password-apps/)
