### ISSUE TITLE
Extension option to login with 1Password not present on iOS 11

### ISSUE THREAD

**Issue by n8chur** [agilebits/onepassword-app-extension#382]
When attempting to show the 1Password action sheet on iOS 11 with the "App Demo for iOS" Demo project, 1Password does not show up as an option.

![img_3106](https://user-images.githubusercontent.com/671271/28942172-3a6925b8-784f-11e7-8ef5-2adda2960541.PNG)

**Comment by n8chur** [comment]
I do have the 1Password app installed on the device that this was tested on.

**Comment by MrRooni** [comment]
Hey there @n8chur. Thanks for raising this issue. I just installed the ACME app on my iPhone 6 Plus running iOS 11 beta 4. When bringing up the share sheet I do see 1Password as an option.

Can you try another app that integrates with 1Password and see if that works properly on that device? Slack is one that I can think of off the top of my head. Also Disney Movies Anywhere or Walmart.

**Comment by gks** [comment]
Hi @n8chur 

It's been 5 days or so at this point so I'm closing this issue, but if you're still encountering trouble please reach out. You can contact us at support+appex@agilebits.com as well if you'd prefer email instead.

**Comment by n8chur** [comment]
I apologize for the delay.

I have not had a chance to try your suggestions yet. I'll give what you suggested a shot and if it's still an issue I'll send you an email.

Thanks!

**Comment by ethansinjin** [comment]
Hey @n8chur,

Does choosing "More" on the bottom provide the option to enable 1Password as an activity?

Also, hope you're well! We should catch up soon

**Comment by n8chur** [comment]
Hey @ethansinjin!

After checking again I do see the option under "More" and after enabling 1Password it does show up in the action sheet.  I'm fairly certain I checked there before submitting this issue... Although it's definitely possible that I only tapped the top "More" option 🤷🏻‍♂️

Thanks!
