### ISSUE TITLE
I want help from 1password developer

### ISSUE THREAD

**Issue by totoourworld** [agilebits/onepassword-app-extension#388]
Hi, Mr.Kyle Swank
This is Sivilay who asked you about the 1password chrome browser extension tech.
I know it is making you annoying.
But only hope in my side is you and your help.
I am really struggle in working in chrome browser form filling in Action Extension of IOS app.
Over 1 month , I am trying to find the way to solve this , but unfortunately , I can't solve.
Last Time , I got valuable tips from you and notices that's only one right way to solve my problem.
At that time you told me that Google chrome send you 'URL' and you send back with username and password.
Can you give me more explain about URL and send back function?
If you can't tell about the send back function because of security , 
Can you teach me about the even 'URL' from Google Chrome.
I am hoping that you can help me with warm mind.
Regards.

**Comment by gks** [comment]
@totoourworld 

As I asked in the previous bug report, can you please email in to get your questions answered. This is not the correct path for getting help. You can email in here: support+appext@agilebits.com

I am closing this, please email instead.
