### ISSUE TITLE
Swift 4 Reworked Version

### ISSUE THREAD

**Issue by fahlout** [agilebits/onepassword-app-extension#391]
I have taken the time to convert the extension to a swift version, Swift 4 to be exact. You can find it here: [PasswordExtension](https://github.com/fahlout/PasswordExtension)

**Comment by ivanmoreno** [comment]
Thank you, I was exactly looking for this

**Comment by fahlout** [comment]
@ivanmoreno Sorry for the late response. I just confirmed that adding "pod 'PasswordExtension'" does indeed add the cocoa pod to the project. Please try it again in your project. Make sure to use pod update instead of pod install as that does not necessarily update your specs.
