### ISSUE TITLE
org-appextension-feature-password-management:// scheme is used by other 

### ISSUE THREAD

**Issue by EmDee** [agilebits/onepassword-app-extension#398]
It seems like some other app is using the same URL scheme, which leads to false positives when we run `OnePasswordExtension.shared().isAppExtensionAvailable()`, even if `1Password` is not installed on the user's device.

Any workaround for that? Do you guys have a more unique scheme? `onepassword://`?

**EDIT:** 
I fasely thought that `PayPal` was using the same scheme, but it turns out they've just integrated `1Password` as well. We have some users on `iPhones 6, iOS 10.1.1` that get those false positives.

**Comment by gks** [comment]
Hi @EmDee 

Sounds like they might have... incorrectly... made their app respond to: `org-appextension-feature-password-management://`

I am not able to duplicate this behavior on iOS 11.2.1. Is it only happening on those exact devices and iOS 10 devices?

**Comment by EmDee** [comment]
Hi @gks!

Seems like it. I couldn't reproduce it on our iOS 11.x devices either. Only happened to a single dev of ours. I was going to see if installing `1P` and deinstalling again would somehow fix the issue, however, `1P` requires iOS 11.

**Comment by gks** [comment]
Hi @EmDee 

Yup, the latest version does indeed require iOS 11. However, the user should be able to attempt to install it, assuming they'd already acquired the app previously, and it'll offer to install an old version. 

It might be easier to find it under App Store > Tap the icon for the user in the top right > Purchased as well. This should prompt to install a previous version (6.x) that works with iOS 10.

**Comment by EmDee** [comment]
Unfortunately that user has never installed `1P` on that device before. I suppose only a system reset will fix the issue now.

Thanks for the help though!
