### ISSUE TITLE
Add constraint to generated password for uppercase and lowercase letters

### ISSUE THREAD

**Issue by ceeK** [agilebits/onepassword-app-extension#404]
One of our business requirements is to ensure passwords contain 1 uppercase and 1 lowercase letter. Unfortunately we can't currently enforce this with the 1Password extension.

Seems like a bit of a crappy requirement to me. Nevertheless I'm wondering if it will be possible in the future.

**Comment by benrondeau** [comment]
[Agilebits](https://twitter.com/agilebits.pdf)

**Comment by 8029616** [comment]
Hello
