### ISSUE TITLE
How to add TOTP secret to the login?

### ISSUE THREAD

**Issue by mfcollins3** [agilebits/onepassword-app-extension#405]
I’m implementing a sign up flow for my application tied to AWS Cognito user pools. I have integration with 1Password for generating the password that I then use to create the user account. At the end of my sign up process, I give the user the choice of configuring MFA using either SMS or TOTP. If the user chooses TOTP, I’m displaying the QR code or have a button that will open the `otpauth://...` URL to open an app like Google Authenticator.

My question is that I would like to have the option to associate the TOTP with the user’s 1Password login record, but I am not sure how to do this since the account has already been created. Is there an API that I can use to update the login with the TOTP secret key?

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, I'm closing out any remaining issues and branches.
