### ISSUE TITLE
findLoginForURLString or not

### ISSUE THREAD

**Issue by brian-ogilvie** [agilebits/onepassword-app-extension#407]
I'm building an app that allows users to view their passwords from any domain. Users have no password that is directly associated with my domain or bundle. I know that they can touch the search button if findLoginForURLString doesn't return any results, but it would be nice if there were a way to open the list of all their logins by default rather than first having to search by URL, which will always return nothing.

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, I'm closing out any remaining issues and branches.
