### ISSUE TITLE
UIWebView vs WKWebView code does not work with Catalyst

### ISSUE THREAD

**Issue by dvshelley** [agilebits/onepassword-app-extension#409]
With Catalyst, UIWebView is not a defined class. So code like the following and others isn't going to compile.

`NSAssert([webView isKindOfClass:[UIWebView class]] || [webView isKindOfClass:[WKWebView class]], @"webView must be an instance of WKWebView or UIWebView.");`

**Comment by Sidetalker** [comment]
Apple is also now preventing new submissions that include UIWebView - I'm forking this repo and removing all references to UIWebView, I'll submit a PR here once I'm done.

**Comment by Sidetalker** [comment]
@dvshelley you should be able to use https://github.com/Sidetalker/onepassword-app-extension/tree/add-framework-support. I'm hesitant to open a PR because I don't have any iOS <= 8 devices to test with + my changes likely break support for that iOS.

**Comment by Sidetalker** [comment]
Opened PR to address this https://github.com/agilebits/onepassword-app-extension/pull/411

**Comment by rudyrichter** [comment]
resolved by #417
