### ISSUE TITLE
UIPopupPresentationController crash in iPad on iOS 12.4

### ISSUE THREAD

**Issue by Wallethub** [agilebits/onepassword-app-extension#412]
Hello,

We started seeing an increasing number of crashes in our app on the iPad device with iOS 12.4 that looks like this:

<img width="595" alt="Screen Shot 2019-09-10 at 5 20 50 PM" src="https://user-images.githubusercontent.com/20915786/64660058-5e37ea00-d447-11e9-99d2-6861d379d7fe.png">

After investigating our code we narrow it down to the possibility that the onepassword extension may be causing this when invoking ``findLoginForURLString`` at line:
```Objective-C
[viewController presentViewController:activityViewController animated:YES completion:nil];
```
Is there a way to resolve this? Or at least determine if this really is the cause or not. Through our tests, we could not replicate the crash.

**Comment by Koze** [comment]
@Wallethub 
I think that you need to set `sender` argument when call `findLoginForURLString` on iPad.
https://github.com/agilebits/onepassword-app-extension/blob/ba96cf1203f6ea749b7c3f4e921b15d577536253/OnePasswordExtension.m#L83

`sender` is used in below for configuring popover.
https://github.com/agilebits/onepassword-app-extension/blob/ba96cf1203f6ea749b7c3f4e921b15d577536253/OnePasswordExtension.m#L478-L484

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, I'm closing out any remaining issues and branches.
