### ISSUE TITLE
Carthage warning "no shared framework schemes" for 1.8.6

### ISSUE THREAD

**Issue by Benuuu** [agilebits/onepassword-app-extension#418]
I tried updating to the latest framework using Carthage and it is failing with the following:

```
*** Skipped building onepassword-extension due to the error:
Dependency "onepassword-extension" has no shared framework schemes for any of the platforms: iOS
```

Seems to be that this was previously patched with tags for framework support (e.g. #325).

**Comment by Sidetalker** [comment]
The Carthage build is working properly on the `add-framework-support` branch. I've updated that branch to include the latest changes from release 1.8.6 in #419.

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, I'm closing out any remaining issues and branches.
