### ISSUE TITLE
Xcode 11.4 Warning: MobileCoreServices renamed to CoreServices

### ISSUE THREAD

**Issue by mccarron** [agilebits/onepassword-app-extension#420]
As of `Xcode 11.4 beta 1 (11N111s)` this extension reports the following warning: 

> MobileCoreServices has been renamed. Use CoreServices instead.

![Screen Shot 2020-02-12 at 4 23 05 PM](https://user-images.githubusercontent.com/45654/74382976-f4d05480-4db3-11ea-869d-612d7f9c8ea1.png)

**Comment by nikolaytw** [comment]
+1 here. Trying to keep project warning free.

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, I'm closing out any remaining issues and branches.
