### ISSUE TITLE
Update Cocoapods for new version

### ISSUE THREAD

**Issue by kevinbhayes** [agilebits/onepassword-app-extension#421]
To-do from customer:

It looks like the repository has been updated. However, the podspec still needs updating. The current version on CocoaPods reads 1.8.5 instead of 1.8.6 which you can see at https://cocoapods.org/pods/1PasswordExtension

**Comment by kevinbhayes** [comment]
From https://agilebits.cerb.me/profiles/ticket/DAT-86682-221/#message5394440

**Comment by diegoreymendez** [comment]
Are you planning to update the extension in CocoaPods?   We need to integrate the latest version as well.

**Comment by pmusolino** [comment]
Same here ✋

**Comment by pedrommcarrasco** [comment]
What's the current status on this?

**Comment by MrRooni** [comment]
Hi folks. CocoaPods support has been something that was driven by external contributors in the past (in particular @tapi ). If someone else would like to take on the mantle that's something we can talk about.

**Comment by pmusolino** [comment]
I can take care of this release on Cocoapods. @MrRooni

**Comment by pedrommcarrasco** [comment]
I can also take care of it if needed 👍

**Comment by tapi** [comment]
@MrRooni I can update the version if needed. Rad was doing it. Think I’m still an owner on trunk. Will check later. Have kids home ATM

**Comment by pmusolino** [comment]
Thanks @tapi!

**Comment by tapi** [comment]
Pushed the update for 1.8.6 to trunk. I’m not at my machine right now but it shows up on cocoapods.org though the search index appears to be stale. Tapping into it does show 1.8.6

Will verify on command line in a bit

**Comment by tapi** [comment]
Seeing 1.8.6 on the command line now. Had to do a `pod repo update` to get it to show up in search even when using the CDN. Everything should be 👍

**Comment by MrRooni** [comment]
Thanks @tapi !

**Comment by jojo0273** [comment]
H
