### ISSUE TITLE
Video in readme gives 404

### ISSUE THREAD

**Issue by lode** [agilebits/onepassword-app-extension#425]
Hej, the video in the readme:

![afbeelding](https://user-images.githubusercontent.com/511245/86047466-3570f780-ba4f-11ea-970a-7fd7ab3776e7.png)

links to https://vimeo.com/102142106, which gives me a 404.

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, i'm going to close this issue out as wont fix.
