### ISSUE TITLE
This commit does several things:

### ISSUE THREAD

**Issue by vity455771** [agilebits/onepassword-app-extension#429]
This commit does several things:
* Moves all projects forward to Xcode 11 format
* Updates build settings and localization targets
* Converts swift projects to Swift 5
* Moves the bar forward from iOS 7 to iOS 9
* Removes all support for UIWebView
* Removes the deprecated call `- (void)fillLoginIntoWebView:(nonnull id)webView forViewController:(nonnull UIViewController *)viewController sender:(nullable id)sender completion:(nonnull OnePasswordSuccessCompletionBlock)completion;`
* Updates Readme.md urls, removes mention of a newsletter

Resolves: #414, #409, #369 

_Originally posted by @rudyrichter in https://github.com/agilebits/onepassword-app-extension/pull/417_

_Originally posted by @vity455771 in https://github.com/agilebits/onepassword-app-extension/issues/428_

_Originally posted by @vity455771 in https://github.com/vity455771/Viktor/issues/1_

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, I'm closing out any remaining issues and branches.
