### ISSUE TITLE
Autofill fails in webviews at multiple websites

### ISSUE THREAD

**Issue by pwightman** [agilebits/onepassword-app-extension#460]
In my app, and the demo app ("WebView Demo for iOS Swift"), autofill correctly identifies the website, but fails to actually fill in the email/password fields for at least the following websites:

* https://plex.tv
* https://appstoreconnect.apple.com (or any other Apple website)
* https://airtable.com/login (only password fills, but not email)

There are surely others, these were found in 5 minutes of going through logins that came to mind. Accessing the extension in Safari works just fine on these sites, however, and makes me think the JavaScript in this repo might be out of date with fixes for identifying fillable fields in the primary app. If that's the case, is there any way we could get an update? Or any ideas on what might be causing this?

The page details collected for plex.tv are:

```
{
   "documentUUID":"oneshotUUID",
   "title":"Watch Free Movies & TV | Stream Smarter with Plex",
   "url":"https://www.plex.tv/",
   "documentURL":"https://www.plex.tv/",
   "forms":{
      
   },
   "fields":[
      
   ],
   "collectedTimestamp":1612384647586
}
```

So it would make sense that the `fillScript` field that gets returned by the extension is just an empty object, since no fields were identified:

```
{}
```

**Comment by rudyrichter** [comment]
In light of the retirement of this extension, I'm closing out any remaining issues and branches.
