### ISSUE TITLE
Visual issues when extension launched in iPad's landscape orientation

### ISSUE THREAD

**Issue by gfiumara** [AgileBits/onepassword-app-extension#73]
![img_0008](https://cloud.githubusercontent.com/assets/419642/3942831/25a4d856-2579-11e4-90ad-2b8f18ae1d03.PNG)

The issues remain if the project is rotated into portrait. Reproducible with [this test project](https://www.dropbox.com/s/ukrbym6ibvhnjnz/1PasswordWebViewTest.zip).

**Comment by radazzouz** [comment]
We believe we fixed most of the lock screen issues in the extension.

The only one left occurs on Touch ID enabled iPads and we already filed an internal bug ( <font size='1' color='grey'><i>ref: OPI-2243</i></font> ) which shall be addressed soon.

![](https://www.evernote.com/shard/s340/sh/bb72d4cf-e949-4b06-b215-6ad47c7f0547/5d5b35230de5adb92a15352370eaec0f/deep/0/-OPI-2243--Visual-glitch-in-Safari-extension-lock-view---JIRA.png)

Please re-open this issue and send us screenshots if you encounter any other lock screen issues in the extension.

Thanks!
